### ISSUE TITLE
[META] bluetooth testing

### ISSUE THREAD

**Issue by moul** [berty/berty#1692]
Issue to discuss about ideas to make bluetooth testing easier,

It can be tricks, tools, etc

I.e.: https://stackoverflow.com/questions/22604305/how-to-use-android-emulator-for-testing-bluetooth-application

Any other ideas?

**Comment by leo-lb** [comment]
@aeddi 

I think this is the only way indeed.

Mocking or emulating bluetooth is no issue, but testing with real world bluetooth with it's packet loss, latency, and the likes, is what's going to be most useful.

That sounds like an exciting eletronics project, that is to build an automated bluetooth test bench!
