### ISSUE TITLE
How difficult would it be to have a react-native-web version?

### ISSUE THREAD

**Issue by moul** [berty/berty#1696]
@gponsinet @n0izn0iz @clegirar what's your opinion?

**Comment by leo-lb** [comment]
What is the goal with a web version?
Just noting that the web is server-centric by nature, both in terms of communication and how it executes code that comes from a server without explicit version changes and signing for users to control updates (necessary to guarantee anything in terms of encryption safety).

See: - https://github.com/w3c/webappsec/issues/538

 Also:
- https://github.com/tasn/webext-signed-pages
- https://www.etesync.com/faq/#signed-pages

There is missing web spec work in that area, there was an ad-hoc attempt in the w3c repo, then someone came with a great idea that we could use SRI on web workers as they can proxy origins and therefore control what comes in and out, enforcing a policy for code changes.

**Comment by n0izn0iz** [comment]
@leo-lb there is two main goals I think (@moul might correct me):
- For easier dev
- For desktop using electron or similar solution

**Comment by leo-lb** [comment]
@n0izn0iz OK. So no online web page?
Electron is embarassing. It's a bloated ram hungry mess. I wish there was a better solution.

**Comment by n0izn0iz** [comment]
@leo-lb I don't think this is planned, for the problems you raised

> I wish there was a better solution

One thing we could do is host the web-app on IPFS but you would still need to run the go daemon locally and we would have to trust an IPFS gateway or serve the IPFS web-ui with the daemon

I think a better solution would be to allow the daemon to also serve the web-app

In both case we could then bundle a "berty.desktop" file that points to the url for ease of use

> Otherwise, there's Revery

I think using revery would require us to rewrite the entire app so it would be better to directly use gtk or qt in that case IMO

**Comment by leo-lb** [comment]
@n0izn0iz 
> One thing we could do is host the web-app on IPFS but you would still need to run the go daemon locally and we would have to trust an IPFS gateway or serve the IPFS web-ui with the daemon
> 
> I think a better solution would be to allow the daemon to also serve the web-app
> 
> In both case we could then bundle a "berty.desktop" file that points to the url for ease of use

Oh that would be awesome! To ship hashes of the webapp. That can be loaded through any IPFS gateway, including a local one.
 
> I think using revery would require us to rewrite the entire app so it would be better to directly use gtk or qt in that case IMO

Agreed.

**Comment by n0izn0iz** [comment]
Electron alternatives
https://github.com/zserge/webview
https://github.com/zserge/lorca

**Comment by leo-lb** [comment]
Also https://webkitgtk.org/ - which is mature and quite nice.

**Comment by J3m5** [comment]
Hi there.
There is also [Tauri](https://github.com/tauri-apps/tauri) as an electron alternative.
