### ISSUE TITLE
feat: Account Pictures

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1698]
depends on #1714 

# v1: no change possible

## own

- [ ] allow to choose an account picture
- [ ] show account picture in bottom right of main screen
- [ ] show account picture in settings screen

## contact

- [ ] embed picture in contact QR
- [ ] send picture in contact request
- [ ] show contact picture in search contact list
- [ ] show contact picture in "New group" contact list
- [ ] show contact picture for 1to1 conversation on "Messages" screen in home

## multimember

- [ ] send picture when joining a multimember group
- [ ] show members pictures in multimember group member list
- [ ] show members pictures for 1to1 conversation 

# v2: allow change

- [ ] allow to select a new picture in settings
- [ ] send picture update to contacts
- [ ] send picture update to all multimember groups joined

**Comment by aeddi** [comment]
Closing because outdated
