### ISSUE TITLE
[chat-mvp] Make SDTSModalCompnent responsive

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1699]
# Looks like this

on iPhone 11 Pro for example:
<img width="397" alt="Screenshot 2020-03-10 at 21 13 43" src="https://user-images.githubusercontent.com/7917064/76355208-246f6f80-6314-11ea-9c0f-a1a0a7d94def.png">

# Should look like this

<img width="401" alt="Screenshot 2020-03-10 at 21 14 03" src="https://user-images.githubusercontent.com/7917064/76355241-35b87c00-6314-11ea-9369-c94651d923e9.png">
(this is on iPhone 11 only)

**Comment by moul** [comment]
old, closing
