### ISSUE TITLE
[chat-mvp] Fix "Search" navigation

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1700]
If you go to "Search" screen then close it (by draging down the sdts component), when you come back to it, it's blank like in screen below.

The only way to reset it by hand is to reload the app.

<img width="406" alt="Screenshot 2020-03-10 at 21 16 20" src="https://user-images.githubusercontent.com/7917064/76355408-89c36080-6314-11ea-8532-79b5b3e21a03.png">

**Comment by moul** [comment]
old, closing
