### ISSUE TITLE
[chat-mvp] multimember conversations member color

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1705]
depends on #1713 

- [ ] choose a pseudo-random color for each member in a group (probably based on the member public key so it's the same for everyone)
- [ ] change messages background color based on member color. This is the background of <img width="281" alt="Screenshot 2020-03-10 at 21 29 24" src="https://user-images.githubusercontent.com/7917064/76356439-3eaa4d00-6316-11ea-8967-5d4974a22e49.png"> displayed here <img width="387" alt="Screenshot 2020-03-10 at 21 30 00" src="https://user-images.githubusercontent.com/7917064/76356493-5386e080-6316-11ea-9115-56e153721e41.png">

**Comment by moul** [comment]
old, closing
