### ISSUE TITLE
[chat-mvp] implement group creation header in conversation

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1706]
This refers to 
<img width="386" alt="Screenshot 2020-03-10 at 21 32 16" src="https://user-images.githubusercontent.com/7917064/76356710-abbde280-6316-11ea-9790-7cb11ccef387.png">
shown here 
<img width="387" alt="Screenshot 2020-03-10 at 21 30 00" src="https://user-images.githubusercontent.com/7917064/76356718-afea0000-6316-11ea-834b-2a742de337a8.png">

**Comment by moul** [comment]
old, closing
