### ISSUE TITLE
[chat-mvp] implement date split in conversations

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1707]
depends on #1718 

This refers to 
<img width="82" alt="Screenshot 2020-03-10 at 21 33 46" src="https://user-images.githubusercontent.com/7917064/76356853-eaec3380-6316-11ea-8ac9-ecd685406784.png">
show here 
<img width="387" alt="Screenshot 2020-03-10 at 21 30 00" src="https://user-images.githubusercontent.com/7917064/76356860-ee7fba80-6316-11ea-8003-4986399ba288.png">
and in 1to1 groups

**Comment by moul** [comment]
old, closing
