### ISSUE TITLE
[chat-mvp] search with a lot of items

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1710]
depends on #1708 

Add lot of items in search screen and make sure it can be used, that scrolling and display work as expected.

The contact is shown used a SDTSModalComponent, this should probably be refactored

<img width="407" alt="Screenshot 2020-03-10 at 21 46 02" src="https://user-images.githubusercontent.com/7917064/76357831-b5484a00-6318-11ea-9ac1-8893c1ed2147.png">

**Comment by moul** [comment]
old, closing
