### ISSUE TITLE
[chat-mvp] prevent from creating a group without members

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1711]
or add a way to invite members after creation

We should prevent from clicking continue in screen below when no members are selected since we have no way to add members afterward currently
<img width="379" alt="Screenshot 2020-03-10 at 21 49 15" src="https://user-images.githubusercontent.com/7917064/76358016-0d7f4c00-6319-11ea-81cb-f95a7cd323b1.png">

**Comment by moul** [comment]
old, closing
