### ISSUE TITLE
Investigate intermitent grpc error on first action

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1731]
On first launch of the app, when we make the first contact request there is sometime a grpc error.

First step is to find a way to reproduce it

On real devices it also happens randomly on some actions

It seems fine if you just dismiss the error but not 100% sure

**Comment by n0izn0iz** [comment]
I think it happens when we call grpc too quickly after starting or reloading the app, something might not have the time to initialize
<img width="408" alt="Screenshot 2020-03-29 at 22 39 27" src="https://user-images.githubusercontent.com/7917064/77860215-428f0800-720e-11ea-86f8-7aade27c5422.png">

**Comment by moul** [comment]
not happening anymore
