### ISSUE TITLE
how to use it  on ios or android?

### ISSUE THREAD

**Issue by jinpengchina** [berty/berty#1766]
how to use it  on ios or android?

**Comment by moul** [comment]
Hi @jinpengchina,

We just open-sourced the repo and will add more documentation for developers in few days

If you just want to run the app, we will also set up a platform so you can just download and run the app

Anyways, note that the app is still in active development and should not be used for real usages, we will release a beta probably at the end of april that will be more interesting even for non-devs

(closing this issue, but feel free to comment/reopen it if you've things to add)
