### ISSUE TITLE
Inconsistent timeouts with go tests

### ISSUE THREAD

**Issue by moul** [berty/berty#1783]
See https://gist.github.com/moul/097fe24920864808eba26cab120bab6d

**Comment by moul** [comment]
The bug seems to be located in the `orbitutil` package, however I just ran the full test suite 10 times without any problem:

```console
$ go test ./internal/orbitutil/ -count=10
ok      berty.tech/berty/v2/go/internal/orbitutil       179.567s
```

**Comment by gfanton** [comment]
Looks like testing node still have default bootstrap, this cause ipfs node to hangout forever in some cases. Removing default bootstrap from testing node fix this issue. (#1778)

**Comment by moul** [comment]
Nice catch!

Are you talking about this line: https://github.com/berty/berty/pull/1778/files#diff-ed434928692099ea013ee9b8d2e00674R52?
