### ISSUE TITLE
CI failing on master but not in the PR

### ISSUE THREAD

**Issue by moul** [berty/berty#1798]
https://buildkite.com/berty/berty/builds/1788#20e210d1-9ea4-4dd7-bb32-096bc105a0f5

[berty_build_1788_bazel-go.log](https://github.com/berty/berty/files/4395104/berty_build_1788_bazel-go.log)

**Comment by leo-lb** [comment]
If you havent seen it yet in the other issue, another CI workflow can solve this.

https://github.com/apps/bors is a bot that can help adopt it.

It allows one to test at merge time, and with the PR merged, rather than at PR submission.

**Comment by n0izn0iz** [comment]
@leo-lb Adding bors would be nice I agree

**Comment by moul** [comment]
not happening anymore
