### ISSUE TITLE
Add documentation in react-native app subfolder root

### ISSUE THREAD

**Issue by ekelen** [berty/berty#1814]
Need at least minimal Up & Running instructions for developers in ./js

- [ ] Software dependency list, at minimum for macOS (xcode, CocoaPods, ...) and installation instructions
- [ ] Makefile usage (abstractions clarified)
- [ ] ...?

Expands subtask of #1754

**Comment by moul** [comment]
Please make it as light as possible

If you have edge cases to manage, manage them in a dedicated "Known issues" section of the README
