### ISSUE TITLE
Add the sender contactPk in GroupMessageEvent if known

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1860]
Currently in the chat app, to know if a message comes from the current user, we check if the message's devicePk is the user's devicePk (returned by InstanceGetConfiguration) which will not work with the real protocol since devicePks are specific to each group

Without adding the contactPk of the sender in GroupMessageEvent it will be quite hard for the chat app to know if a message comes from the current user when using the real protocol (from what I understand)

**Comment by moul** [comment]
old, closing
