### ISSUE TITLE
Do something for screen with tabs (infos, devices, etc.)

### ISSUE THREAD

**Issue by clegirar** [berty/berty#1868]
Find datas to put in all tabs:

![Annotation 2020-04-15 144451](https://user-images.githubusercontent.com/33428384/79338493-b0824180-7f27-11ea-933b-b677940b4f8d.png)

**Comment by n0izn0iz** [comment]
tabs with missing data:
- info, devices in "add this contact", "incoming contact request", "outgoing contact request" and "contact chat settings"
- devices in "my berty id"

**Comment by n0izn0iz** [comment]
I think that we should improve the difference between a normal tab and a disabled one.
In this screen it's not intuitive that the devices tab is disabled and not just a bug
<img width="263" alt="Screenshot 2020-04-22 at 06 22 12" src="https://user-images.githubusercontent.com/7917064/79940335-b74a1080-8461-11ea-84dc-70a4882a997a.png">
