### ISSUE TITLE
Cleanup berty-storybook

### ISSUE THREAD

**Issue by clegirar** [berty/berty#1930]
Cleanup berty-storybook package -> duplicate code, unused variables/functions, bad types

onboarding: 
- [ ] Onboarding.tsx

chat/shared-components:
- [ ] Chat.tsx
- [ ] Message.tsx

chat:
- [ ] Chat.tsx
- [ ] ChatGroup.tsx
- [ ] ChatSettings.tsx
- [ ] ContactChatSettings.tsx
- [ ] GroupChatSettings.tsx

main:
- [ ] ContactRequest.tsx
- [ ] CreateGroup.tsx
- [ ] Footer.tsx
- [ ] GroupRequest.tsx
- [ ] List.tsx
- [ ] ListModal.tsx
- [ ] RequestSent.tsx
- [ ] Scan.tsx
- [ ] ScanRequest.tsx
- [ ] Search.tsx

modals:
- [ ] AddThisContact.tsx
- [ ] InvalidScan.tsx
- [ ] SendContactRequest.tsx

settings:
- [ ] AboutBerty.tsx
- [ ] AppUpdates.tsx
- [ ] BlockedContacts.tsx
- [ ] Bluetooth.tsx
- [ ] DevTools.tsx
- [ ] EditProfile.tsx
- [ ] Help.tsx
- [ ] Home.tsx
- [ ] Mode.tsx
- [ ] MyBertyId.tsx
- [ ] Notifications.tsx
- [ ] TermsOfUse.tsx

shared-components:
- [ ] CircleAvatar.tsx
- [ ] Fallback.tsx
- [ ] FingerprintContent.tsx
- [ ] Footer.tsx
- [ ] FromNow.tsx
- [ ] Header.tsx
- [ ] Modal.tsx
- [ ] ProceduralCircleAvatar.tsx
- [ ] Request.tsx
- [ ] SDTSModalComponent.tsx
- [ ] SettingsButtons.tsx
- [ ] TabBar.tsx

**Comment by moul** [comment]
@clegirar is this issue still relevant, or can we close it?

**Comment by clegirar** [comment]
We can close it
