### ISSUE TITLE
What is your plan for spam messages if this network gets big?

### ISSUE THREAD

**Issue by wormeyman** [berty/berty#1934]
I saw a post about this on Reddit and I think it is really neat that you do not require a phone number or an email address. However with such little authentication required how do you prevent a ton of bots registering and sending spam?

**Comment by leo-lb** [comment]
@wormeyman It's a distributed network so there isnt any authority to tell who is a spammer or not.

However, Berty can rely on users themselves and who they add as a friend and so on. I believe that is the plan here. You wont be able to send a message to someone on the network without establishing trust first, either by adding as a contact, or having a mutual contact through which (relative) trust can also be obtained.

**Comment by aeddi** [comment]
A relevant answer was given, I close to archive.
