### ISSUE TITLE
message is never sent in corner case

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#1940]
I saw this during testing with the real protocol

repro:
- need app A and B that are added as contact
- close B
- send message from A to B
- close A
- open B
- send message from B to A
- open A
- problem: message from A is never received by B (the other message is propagated fine)

not sure if the problem comes from the app or the protocol but I don't get why the app would have a problem in this case

**Comment by moul** [comment]
Is this issue still relevant, or can we close it?

**Comment by n0izn0iz** [comment]
we can close
