### ISSUE TITLE
Text is truncated in headers and buttons on some devices

### ISSUE THREAD

**Issue by ekelen** [berty/berty#1983]
- [ ] Widgets in Add Contact component
  - Depends on #1933 
- [ ] 'About Berty' header
- [ ] 'Dev tools' header

These should not be truncated, per the mockups here: https://assets.berty.tech/categories/app__v2.4/

Screenshots are from iPhone 8 zoomed view, can be approximately replicated by using iPhone 5s in simulator.

<img src="https://user-images.githubusercontent.com/24300177/83051690-a5562180-a04e-11ea-9d2f-dfbec8440091.png" height=400/>

<img src="https://user-images.githubusercontent.com/24300177/83052312-6bd1e600-a04f-11ea-805b-9650d4c7ac66.png" height=400/>

<img src="https://user-images.githubusercontent.com/24300177/83052094-20b7d300-a04f-11ea-8423-1c7fe0f9c42b.png" height=400 />

**Comment by moul** [comment]
🕚 Closing as no recent updates. Please reopen if you need any updates to this ticket.
