### ISSUE TITLE
Add swipe gesture support to navigate between messages and message list

### ISSUE THREAD

**Issue by ekelen** [berty/berty#1994]
UX feature suggestion

Brought up in testing session #3

**Comment by ekelen** [comment]
This was already implemented (iOS 11), you added in #1927 looks like. Is there something missing from current implementation or can this be closed @clegirar ?

**Comment by n0izn0iz** [comment]
#1927 is about swiping *down* the keyboard to close it in the messages list
I think this is about swiping left from the messages list to the conversations list

**Comment by ekelen** [comment]
Ah okay my bad for the PR.

This seems to already be implemented, maybe I am missing something. If I swipe right-to-left in the list, I go to that conversation. If I swipe left-to-right on the header of the conversation, I go back to the list. (iOS 11.something)

**Comment by n0izn0iz** [comment]
Maybe you're just pressing the button in both cases? (from react-native point of view)

Or maybe not, if I release the press outside of the button it doesn't navigate on iOS 13.5 so maybe it's a version thing

Also the swipe from messages to the conversation list should happen from the whole page (not just the header) I think (maybe @zooma2k18 can confirm?)

**Comment by zooma2k18** [comment]
yes, I confirm, the whole page is better, for lateral swipe on this case

**Comment by n0izn0iz** [comment]
My bad, I can swipe from the messages list to the conversations list if I start the swipe at the very edge (the whole left edge of the screen)

**Comment by ekelen** [comment]
Okay, so if I understand correctly, I'll enable the swipe back to the message list from the entire chatroom screen, but consider the list->chatroom swipe already implemented.

**Comment by n0izn0iz** [comment]
If by "message list" you meant "conversations list", yes.

**Comment by moul** [comment]
I think this was fixed in a previous PR, please reopen and add more details if you think it needs more work.
