### ISSUE TITLE
Switch to typed-redux-saga

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#2021]
Currently we loose typing when we use `redux-saga` effects, to keep typings we need to use typescript's `as` keyword which is cumbersome and error-prone

See their readme: https://github.com/agiledigital/typed-redux-saga

I already added a rough `typedCall` util in our codebase but this seems a lot better

For reference, here is the issue to add this functionality directly in `redux-saga` repo
https://github.com/redux-saga/redux-saga/pull/2053
It's not moving currently

**Comment by moul** [comment]
🕚 Closing as no recent updates. Please reopen if you need any updates to this ticket.
