### ISSUE TITLE
Yarn install takes too long

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#2025]
When working on the app, everyone is wary of editing (add, remove, bump, move) dependencies since running yarn install takes so long

I think this is related to the sheer number of files in dependencies (300k+ I believe)
Couple of ideas:
- use yarn "zero install" or something similar
- identify the dependencies with the most files and remove them

**Comment by moul** [comment]
I'm pretty sure this is common in this ecosystem, someone should already have made something to help

cc @gponsinet, @gorhgorh, any idea?

**Comment by gponsinet** [comment]
It is a common problem of JavaScript environment. You can try pnpm, it should help

**Comment by n0izn0iz** [comment]
@gponsinet wow, the benchmarks are impressive
https://github.com/pnpm/benchmarks-of-javascript-package-managers
thanks for the tip

**Comment by gponsinet** [comment]
Yep, they speed up x2 from v4 to v5

**Comment by gponsinet** [comment]
I think they use hard link so you have only one version of files in your filesystem

**Comment by gponsinet** [comment]
> Yep, they speed up x2 from v4 to v5

35% for some cases sorry

https://twitter.com/pnpmjs/status/1254174183124279300

**Comment by moul** [comment]
🕚 Closing as no recent updates. Please reopen if you need any updates to this ticket.
