### ISSUE TITLE
Mobile app doesn't compile

### ISSUE THREAD

**Issue by alexarsh** [berty/berty#2053]
While trying to run 'device="test" make run.ios', getting the following error:

/tmp/berty/js/.env.development
GO111MODULE=off go get golang.org/x/mobile/cmd/gomobile
cd /private/tmp/berty/js/packages/berty-app && gomobile init
mkdir -p /private/tmp/berty/js/packages/go-bridge/ios/Frameworks
GO111MODULE=off gomobile bind -o /private/tmp/berty/js/packages/go-bridge/ios/Frameworks/Bertybridge.framework -v -target ios berty.tech/berty/go/framework/bertybridge
gomobile: gobind was not found. Please run gomobile init before trying again.
make: *** [/private/tmp/berty/js/packages/go-bridge/ios/Frameworks] Error 1

'gomobile init' was run and 'gomobile bind' command exists.
Any ideas what can be done?

**Comment by aeddi** [comment]
It seems to be a problem with go / gomobile.

Are your go env variables set correctly?
Is `gobind` bin in your `$GOPATH/bin`?
Has 1$GOPATH/bin1 been added to your path?

**Comment by alexarsh** [comment]
Yes. Here it is:

% ls -l $GOPATH/bin/
total 34320
-rwxr-xr-x  1 alex  staff  7783584 Jun 11 15:36 gobind
-rwxr-xr-x  1 alex  staff  9781764 Jun 11 15:36 gomobile

**Comment by aeddi** [comment]
Has `$GOPATH/bin` been added to your `PATH` env variable?

**Comment by alexarsh** [comment]
Yep. That one was missing. Now when the app loads I see the following error:
"No Bundle URL present"
What am I missing?

**Comment by aeddi** [comment]
Is metro running as mentioned in the README?
https://github.com/berty/berty/tree/master/js#1-run-required-services

**Comment by alexarsh** [comment]
Metro is not running indeed. Running 'make start.metro' gives the following exception:

  const cmd = _commander().default.command(command.name).action(async function handleAction(...args) {
                                                                ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/private/tmp/berty/js/packages/berty-app/node_modules/react-native/cli.js:13:11)
make: *** [start.metro] Error 1

**Comment by aeddi** [comment]
Can you install/update to a recent version all the requirements listed in the README?
The similar problems I find on the subject seem to be due to a too old version of node for example.

**Comment by alexarsh** [comment]
Yes. It was a node version. I think it can be good to update the README with the exact dependencies and versions.
The next problem is how to run 2 simulators simultaneously?
When I follow the README, every new instance runs in the same simulator for some reason, although I give them different names

**Comment by aeddi** [comment]
Is the name you give them the name of a device/simulator on your machine?

You can list the installed simulators using `xcrun simctl list devices` https://reactnative.dev/docs/running-on-simulator-ios#specifying-a-device

**Comment by alexarsh** [comment]
Yep. Now it's working with the right names. 
So I am able to start 2 simulators and login. Is there some explanation how to use the app?
I would like to write messages between 2 simulators.
For some reason I see that the "send" button is disabled in sample groups and I have no option to add users (can't share QR code in simulator) or add a new group.
So how can it be done?

**Comment by aeddi** [comment]
When you are on a simulator:
- You can copy the link using this button:

<img width="349" alt="Screenshot_2020-06-11_at_18 04 07" src="https://user-images.githubusercontent.com/5222525/84411128-7de68380-ac0e-11ea-95b3-6ccc7ec4e217.png">
<img width="90" alt="Screenshot_2020-06-11_at_18 04 11" src="https://user-images.githubusercontent.com/5222525/84411118-7d4ded00-ac0e-11ea-9e97-477859215c5a.png">

- And you can paste it in this hidden field:

<img width="371" alt="Screenshot_2020-06-11_at_18 04 20" src="https://user-images.githubusercontent.com/5222525/84411670-a9696e00-ac0e-11ea-863b-4df2e276418b.png">
<img width="344" alt="Screenshot_2020-06-11_at_18 04 48" src="https://user-images.githubusercontent.com/5222525/84411707-ac645e80-ac0e-11ea-8e91-191c26c90d8e.png">


However, since the questions become off-topic now that the app is compiled I will close this issue, please open another one to ask questions about using the app.

**Comment by alexarsh** [comment]
Sure. Thanks a lot!
