### ISSUE TITLE
[iOS] Support https://berty.tech deep links

### ISSUE THREAD

**Issue by glouvigny** [berty/berty#2054]
Things to edit to support deep linking https://berty.tech links on the iOS app:

* [ ] Add the "Associated Domains" capability to the signing profile
* [ ] The XCode project (list supported domains)
* [ ] The website (by adding a `/.well-known/apple-app-site-association` JSON file on the berty.tech domain)

See https://developer.apple.com/documentation/safariservices/supporting_associated_domains_in_your_app for more info.

File path for the `apple-app-site-association` file seem to be different since iOS 13, we might have to keep both [the existing file (albeit adapting its content)](https://github.com/berty/www.berty.tech/blob/master/bertytech/static/apple-app-site-association) and create a new one for iOS <= 12 compatibility

**Comment by n0izn0iz** [comment]
We also need to add the "Associated Domains" capability to the signing profile

**Comment by moul** [comment]
🕚 Closing as no recent updates. Please reopen if you need any updates to this ticket.
