### ISSUE TITLE
Messenger search does not work with very large volumes of data

### ISSUE THREAD

**Issue by ekelen** [berty/berty#2083]
Results need to be retrieved and displayed incrementally.

In the meantime, we can at least set some cutoff limit for number of items to search.

At the moment, if we have a million messages and search the letter 'a', search feature will not be too usable. 

Consider using fusejs (already installed it seems) and/or different implementations of delivering search results so we can achieve this.

(Fusejs or similar could also help with fuzzy searches, etc.)

**Comment by moul** [comment]
to improve performance, we should probably implement it from the bertymessenger package and use sqlite-based searching
