### ISSUE TITLE
Add in-app faker and dev fake mode

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#2168]
# Why

This is to help with ui dev and testing

1) The ui devs need a way to work on pure ui components without running into network/protocol/grpc/desync issues
2) The ui testers need a way to create conversations and contact requests alone with only one device

Storybook is broken currently and it would require maintenance so it's not a very good option for the first problem

If we add an in-app faker for ui tests we could use that for ui dev too if we also add an app mode where we don't start the berty node

# Breakdown

## Add in-app faker
Add a dev-menu button or submenu to create fake conversations, contacts and messages

- [ ] change "fake" kind in conversations to a boolean to simplify handling fakes
- [ ] add a command to create fake conversations
    - [ ] if oneToOne, create/link the contact
    - [ ] take AppMessage list as argument and create/link the messages
- [ ] add fake boolean in contact state
- [ ] add a command to create fake contacts requests
- [ ] add noops in transactions or components when the entities are fake
- [ ] add commands to delete fakes (if the boolean is set -> delete)
- [ ] add ui in dev-tools to create and delete fakes (randomized)
- [ ] bonus: if fake incoming contact request is accepted, create fake conversation with random messages

## Add fake mode in dev
Add a "fake" mode (in addition to "embeded" and "external") to the app in dev that does not start a node to save resources for ui dev with limited resources

- [ ] add "fake" mode choice to account creation ui
- [ ] change app's startup code to not start the node in "fake" mode and populate the store with the data that should be returned by the node on startup
- [ ] change deep links/qr scaning to a noop in fake mode
- [ ] bonus: add noop/mock client that is used in fake mode, in case a client transaction is called 
 
## Remove storybook

With these changes storybook is not needed anymore

- [ ] remove storybook related packages and files

**Comment by moul** [comment]
Is this issue still relevant, or can we close it?

**Comment by n0izn0iz** [comment]
this is done
