### ISSUE TITLE
Background color in Home screen

### ISSUE THREAD

**Issue by clegirar** [berty/berty#2185]
<img width="150" alt="Capture d’écran 2020-07-22 à 11 55 15" src="https://user-images.githubusercontent.com/33428384/88163129-815c2a00-cc12-11ea-856b-ffb9b82796d6.png">

Actually in home screen, when we have requests the background color changes to blue else it's white.

The problem here, is that when we have requests and we scroll up the `messages` list, the background color stay blue.
I've tried something like when we scroll up, the background color change in white and when we scroll down it change in blue.

But when the bounce becomes at the origin position, it was considered like a scroll up or a scroll down, respectively when we are at the top and at the bottom.

**Comment by moul** [comment]
I think this was fixed in a previous PR, please reopen and add more details if you think it needs more work.
