### ISSUE TITLE
messenger: scanner is not reset on result dismiss

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#2272]

**Comment by moul** [comment]
@n0izn0iz do you have more details?

is it something shake-able? if yes, I suggest to close this one and continue with the shake issue containing debugging metadata

**Comment by n0izn0iz** [comment]
not really but I can provide the details here:
after scanning a qr, whenyoudo an action that `goBack` to the QR scan, the scanner will not react to codes anymore
the solution is to reset the scanner on focus I think

**Comment by clegirar** [comment]
It's the props `reactivate`, in the lib's component that we use (https://github.com/moaazsidat/react-native-qrcode-scanner) that reactivate the scanning ability of the component, by default the `QRCodeScanner` will not scan another code until it is re-rendered
