### ISSUE TITLE
Remove the global var gListener in the Multipeer Connectivity (mc) driver

### ISSUE THREAD

**Issue by D4ryl00** [berty/berty#2288]
`gListener` is a global variable needed by `HandleFoundPeer` to inform libp2p a new peer was found.
`HandleFoundPeer` is called by the mc driver with the remote peer ID as argument like this:
`(Driver side) New connection -> (Transporter side) HandleFoundPeer()`

Having a global variable for the listener is not good for concurrency programmation.

The question is what is the best solution to remove gListener.

One solution I thought is that the transporter `Listen.Accept()` method calls a synchronous function of the driver which returns when a new peer is found, like this:
`(Transporter side) Listen.Accept() -> (Driver side) Accept()

**Comment by moul** [comment]
The rest of the driver does not support having multiple instances at the same time, so for now:

* keep the global (even if we make everything to never have some)
* use `sync.Once` to init a singleton instance

**Comment by phanhuynhquy** [comment]
@D4ryl00 : if you're working on this issue, there is small error could you help me to fix it?
in go/internal/multipeer-connectivity-transport/discovery.go\HandleFoundPeer():
```
// Checks if a listener is currently running.
	if gListener == nil || gListener.ctx.Err() != nil {
		logger.Error("discovery handle peer failed: listener not running", zap.Error(gListener.ctx.Err()))
		return false
	}
```
if gListener is nil, then we will have a crash when call zap.Error(gListener.ctx.Err()))

**Comment by D4ryl00** [comment]
@phanhuynhquy yes I'm working on it, thx!
https://github.com/berty/berty/pull/2289

**Comment by moul** [comment]
Is this issue still relevant, or can we close it?
