### ISSUE TITLE
Investigate leak in manager_test.go

### ISSUE THREAD

**Issue by phanhuynhquy** [berty/berty#2330]
Below is my investigate for leakages `manager_test.go` - still on-going
### 1. Testcase TestUnstableFlagsLeak
No leak by berty code, the leak come from upstream library, these leaks here also happen in other test cases in this 
Add below code to resolve:
```
defer goleak.VerifyNone(t,
		goleak.IgnoreTopFunction("github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine"), // global writer created at github.com/ipfs/go-log@v1.0.4/writer/option.go, refer by github.com/ipfs/, like go-bitswap
		goleak.IgnoreTopFunction("go.opencensus.io/stats/view.(*worker).start"),              // called by init() in berty/go/internal/grpcutil/server.go
		goleak.IgnoreTopFunction("github.com/desertbit/timer.timerRoutine"),                  // called by init() in github.com/desertbit/timer/timers.go, refer in grpc-web
	)
```
##### 1. `github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).background `
-> there is no peerstore closing code in upstream code. 

##### 2. `github.com/lucas-clemente/quic-go.newClosedLocalSession`
-> This leak happen due to the shutdown will be triggered to run after 5 seconds after call shutdown().
Search code : 
```
time.AfterFunc(h.deleteRetiredSessionsAfter, func() {
		h.mutex.Lock()
		handler.Close()
		delete(h.handlers, string(id))
		h.mutex.Unlock()
	})
```
**_So need delay > 5 seconds after closing manager_**

##### 7. `github.com/jbenet/goprocess/periodic.callOnTicker.func1`
-> TBD - but I think this is problem of upstream library

##### 1. berty.tech/berty/v2/go/internal/ipfsutil.ServeHTTPWebui.func1
-> **_Need to add code to graceful shutdown Http server when closing manager_**

**Comment by moul** [comment]
:+1: ok thank you for the report,

can you start fixing as much as you can without external contributions:

* no problem to wait for 6 seconds in the tests that are explicitly here to check if there are leaks
* also you can ignore with `Goleak.IgnoreTopLevelFunction()` some other ones

btw, the top goal here is not to just have unit tests pass, but to be able to stop/start a full node in the same process with as much leaking as possible

**Comment by phanhuynhquy** [comment]
Sure @moul , just put here for me for tracking. Will look at remain leak points, then will create PR to fix both test + berty lib code.

**Comment by phanhuynhquy** [comment]
Fixed PR: https://github.com/berty/berty/pull/2354
