### ISSUE TITLE
On Android if the UI crash the app closes

### ISSUE THREAD

**Issue by Jorropo** [berty/berty#2397]
On Android if the UI crash the app closes instantly so it's impossible to read the call-stack of the crash (I can spot it for a few tenth of seconds).

**Comment by moul** [comment]
the next time it happens, can you try shaking your phone to see if everything is broken or if shake is still working? btw, even if the screen is completely white, shake may offer some helpful context in the report

**Comment by jefft0** [comment]
Closing as resolved in a recent release.
