### ISSUE TITLE
Android App does not fill top portion of UI 

### ISSUE THREAD

**Issue by zachoooo** [berty/berty#2422]
I'm using the pixel 4A phone which has a cutout in the top left for the selfie camera. Many apps make the background of the notification bar match the background of the app so it feels seamless. As you can see in this photo, that whole portion is grayed out. This occurs on the search and setting pages too. The app would look a lot better if that space was filled with a matching color.
![screenshot](https://user-images.githubusercontent.com/1052396/95132186-354e5b00-0714-11eb-9a6a-817e3080f30b.png)
![screenshot2](https://user-images.githubusercontent.com/1052396/95132471-adb51c00-0714-11eb-869d-f91c50689445.png)

Here is a mockup of how the other page should look:
![image](https://user-images.githubusercontent.com/1052396/95132933-5d8a8980-0715-11eb-9282-9733cdb693a1.png)

**Comment by aeddi** [comment]
Should be fixed by now:
- https://github.com/berty/berty/blob/master/js/packages/components/main/home/Home.tsx#L174
- https://github.com/berty/berty/blob/master/js/packages/components/settings/Home.tsx#L304
