### ISSUE TITLE
Improve Background on Settings and Profile Screens

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2547]
On Settings and  Profile screens, Blue Background and White Background must join just behind buttons.

**Current :** 
![current screen settings](https://user-images.githubusercontent.com/37345040/96863586-61354480-1467-11eb-9c83-044c82140c87.png)

**Expected :** 
![newsettings](https://user-images.githubusercontent.com/37345040/96863657-7ca04f80-1467-11eb-9017-2fec2fb2cd1d.png)

**Comment by SochinskySamuil** [comment]
hello

**Comment by SochinskySamuil** [comment]
Are you here?

**Comment by zxxma** [comment]
Hello!
Yep, but feel free to join us on discord if you need quick answer
