### ISSUE TITLE
Facing issue while application setup for React Native

### ISSUE THREAD

**Issue by Rajveer123** [berty/berty#2609]
I am executing 'make ios.debug' command from js folder. I have installed yarn, go (go1.15.3 darwin/amd64 version), I have Xcode 12.2 already installed , MacOS Catallina. As I have to go through automate process by using your commands mentioned in README file so I am doing exactly same but facing below error. 

INDMAC:js oteredesai$ make ios.debug
cd .. && go mod download
cd .. && go run golang.org/x/mobile/cmd/gomobile init
mkdir -p "ios/Frameworks"
cd .. && GO111MODULE=on go run golang.org/x/mobile/cmd/gomobile bind \
                -o js/ios/Frameworks/Bertybridge.framework \
                -v -ldflags="-X berty.tech/berty/v2/go/pkg/bertyversion.VcsRef=`git rev-parse --short HEAD` -X berty.tech/berty/v2/go/pkg/bertyversion.Version=`go run -mod=readonly -modfile=../go.mod github.com/mdomke/git-semver/v5`" \
                -target ios \
                -iosversion 12.0 \
                ./go/framework/bertybridge
go: open ../go.mod: no such file or directory
/var/folders/3r/7z1yv2gs3dv3k18gxy_34y240000gp/T/go-build093221882/b001/exe/gomobile: gobind was not found. Please run gomobile init before trying again.
exit status 1
make: *** [ios/Frameworks/Bertybridge.framework] Error 1

Can anyone let me know what I am missing here.

Thanks

**Comment by aeddi** [comment]
Hi,

Sorry for the response time, we didn't have an effective process or notification system set up to handle issues and PRs from the community. From now on we should be much more responsive.

Can you try to build the project again ? A lot of fixes have been merged since then.
