### ISSUE TITLE
Improve Swipe effects in app similar to Deck Swiper

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2614]
We would love to improve swipes behaviors in app (like Deck Swiper), moving between desks.
Example: From Settings screen to Home screen (Conversation list), or in Profile, Scan QR, Create New group.

This lib can be used : 
https://github.com/alexbrillant/react-native-deck-swiper

The "moving screen" have also to be improved, with radius & blur on background.
Current behavior not optimized : 
![Capture_decran_2020-10-28_a_12 45 11](https://user-images.githubusercontent.com/37345040/97710160-ac7cd200-1abb-11eb-8ba9-8f6079cc4486.png)

**Comment by sakul-budhathoki** [comment]
I am not sure of implementing Deck Swiper libraries with react-navigation. We can achieve swipe gesture; vertical or horizontal. And can customize animation and transition of the screen navigation. 
Here is example of horizontal swipe gesture and custom transition effect. 
![navigation](https://user-images.githubusercontent.com/13379067/99669933-dd876b80-2a97-11eb-814d-2ffe7f5eeabb.gif)

**Comment by zxxma** [comment]
It looks neat @sakul-budhathoki 👍 
thanks for this proposal, let's go for this.

**Comment by sakul-budhathoki** [comment]
Done in #2754
