### ISSUE TITLE
Create a react-native-dropdown-picker like 

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2627]
Create a react-native-dropdown-picker like.
It can receive style props (it will look like all other settings buttons). No animation on click.
Feel free to ping zôÖma & clemsss on discord to discuss about this issue!

**Comment by clegirar** [comment]
I'm using this lib for the moment https://github.com/hossein-zare/react-native-dropdown-picker

**Comment by glouvigny** [comment]
Maybe you should consider opening a full screen with a list of options to pick from, instead of a tiny drop down selector, in terms of UX it might be a better solution for such cases

**Comment by clegirar** [comment]
I think that if a full screen is necessary, we'll add a screen and follow the actual UI of settings screens, a custom component is not useful if we want a full screen
Here de need a dropdown for particularly behavior like a dropdown or languages, for this example a full screen is too much
