### ISSUE TITLE
Find (or create) a lib for Custom QR Design

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2712]
We currently use B&W default QR design for Berty Account, the idea is to reproduce this design : 

**Expected QR Design :** 
![image](https://user-images.githubusercontent.com/37345040/98925627-83563b80-24d6-11eb-847d-8d8c67d4dbaf.png)

**This QR will take place in Settings, for example, and in "Share my ID" :** 
![newsettings](https://user-images.githubusercontent.com/37345040/98927426-ce714e00-24d8-11eb-8d28-a98bc611dee4.png)

**Comment by n0izn0iz** [comment]
Keep in mind it must not use an external service and it needs to be performant (something relying on `react-native-svg` for example)

**Comment by sakul-budhathoki** [comment]
@zxxma Can you share logo used in expected QR design? 
@n0izn0iz I modified existing react-native-qrcode-svg package to match our expected design.

**Comment by n0izn0iz** [comment]
@sakul-budhathoki this is exactly what I had in mind, nicely done

**Comment by zxxma** [comment]
Hi @sakul-budhathoki 
Great job, quick & clean. 👏 

Here is the logo svg version!
https://assets.berty.tech/picto-1_berty_picto.svg/

**Comment by sakul-budhathoki** [comment]
Done in #2723
