### ISSUE TITLE
Copy&Paste function in conversations

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2743]
We need to add the copy & paste function in conversations.

**Comment by sakul-budhathoki** [comment]
We can copy whole text of message using `selectable` props of Text of react-native. For selecting text partially we have to use https://github.com/Astrocoders/react-native-selectable-text

**Comment by sakul-budhathoki** [comment]
Using `selectable` props:-
![copypaste](https://user-images.githubusercontent.com/13379067/99766800-f2acda80-2b29-11eb-96cd-824371ff23ed.gif)

**Comment by clegirar** [comment]
Good 👍 I have a PR in WIP and soon finished that refacto `Message` component, i prefer to merge it before you start your implem, i ping you when it's merged 👍 
And for the lib, i saw some other opinions and i also see, that a `TextInput` with `editable` props as false in iOS is possible, and like that we don't need to install a native library
I don't really have an opinion on this 👍 I just offer an other possibility 👍 we can test both and will see 🙂

**Comment by sakul-budhathoki** [comment]
Hi @clegirar . I couldn't select text with `TextInput` with` editable={false}` on iOS. Let me know if I miss something.

Using  https://github.com/Astrocoders/react-native-selectable-text  will not help much for us as it doesn't provide copy features. So, I suggest `Text` with `selectable` props to select all text at once in iOS, and for Android it has better support. 

![copy](https://user-images.githubusercontent.com/13379067/99903360-ff792c00-2ceb-11eb-96cd-3573af72978d.gif)
