### ISSUE TITLE
Optimize readability Debug Mode informations

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2762]
We need to optimize informations in conversations when Debug mode is activated (Devtool).
Maybe try to reduce the police size, align text on right side, and put line between types of informations.

![debug](https://user-images.githubusercontent.com/37345040/99731825-bc864100-2abe-11eb-932f-92325d0db7db.jpg)

**Comment by sakul-budhathoki** [comment]
How can I reproduce same screen as above?
I enabled Debug from Dev tools, but didn't seen such text in conversation.

**Comment by zxxma** [comment]
You'll need to create a multimember conversation. This screen notify peers connexions, so if you want to reproduce it, we need to sync & organize a little testing session together.
I can do it for you, or with you if you want. Just ping me on Discord, and we'll do it together.

**Comment by moul** [comment]
done in #2777
