### ISSUE TITLE
When a msg is very long in a conversation, we need to reduce it and and click on "Read more"

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2763]
When people write very long messages, in 1to1 conversation and in Group conversations, we need a limit to prevent messages that are too long from taking up the user's entire screen.
Displaying a "Read more" at the end of the message and when user click, then deliver the all message.

In this example, it's in a group conversation.
For the moment, I propose to test a limit of **325 characters**.

![ReadMore](https://user-images.githubusercontent.com/37345040/99733162-0708bd00-2ac1-11eb-9d84-64297afd05b3.png)
.

**Comment by sakul-budhathoki** [comment]
Done in #2776
