### ISSUE TITLE
Files Option (+) Button in conversation. 

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2783]
In conversations, we need to add this new button, which will allow to send specific things in conversations like : 
- Audio files (by direct recording mode)
- Pictures & Video 
- Specific Emojis & Bertyzzz (upcoming feature)

This menu closes as soon as you click anywhere else.

![SendMode](https://user-images.githubusercontent.com/37345040/99940421-69d1b100-2d6c-11eb-90cc-997c5965113b.png)

**Comment by glouvigny** [comment]
Maybe "Send a photo/video" or "Send from gallery/camera roll" depending on the platform would have been a better name for the "Access to Media Gallery" button. Separating "Bertyzzz" (what is this feature>) and emoji buttons would have been better.

I think the UI for sending attachments in other apps is better (it can be a grid of options, directly last pictures taken and/or quick options in the input field for common choices -- ie. voice message)

Here are options from some apps for reference:

WhatsApp:
![Screenshot_20201125-183753_WhatsApp](https://user-images.githubusercontent.com/486708/100264182-cb517580-2f4e-11eb-88d4-0f7c74cdb6ef.jpg)

Signal:
![Screenshot_20201125-183910_Signal](https://user-images.githubusercontent.com/486708/100264185-cc82a280-2f4e-11eb-8dc0-fd9100688698.jpg)

Telegram:
![Screenshot_20201125-184045_Telegram](https://user-images.githubusercontent.com/486708/100264186-cc82a280-2f4e-11eb-9109-a0f20ab420aa.jpg)

Line:
![Screenshot_20201125-184154_LINE](https://user-images.githubusercontent.com/486708/100264188-cd1b3900-2f4e-11eb-99b6-f430311de08b.jpg)

Kakao:
![Screenshot_20201125-184216_KakaoTalk](https://user-images.githubusercontent.com/486708/100264190-cd1b3900-2f4e-11eb-8eaf-58174a37fad3.jpg)

WeChat:
![Screenshot_20201125-184244_WeChat](https://user-images.githubusercontent.com/486708/100264192-cdb3cf80-2f4e-11eb-9c0e-87c521cefe04.jpg)

FB Messenger:
![Screenshot_20201125-184456_Messenger](https://user-images.githubusercontent.com/486708/100264195-cdb3cf80-2f4e-11eb-9e3b-924d92d0fac7.jpg)

**Comment by zxxma** [comment]
Thanks for inputs! 

Just to explain my idea and vision about Emojis & Bertyzzz :   
The idea was to have a specific behavior on this button, when user click on it one time, it would open a gallery of creative animated emojis (I would give example of Telegram Badges, which are organized as "Pack" the user can download and add to his own 'customized emoji gallery'.).
So, by clicking one time on this button, he could choose his "pack" of Bertyzzz (or use the Default pack also).

Then, after this, when he click with a press time from 1sec to 4 sec, this button becomes a kind of "funny propulser".
Ex: if I press it during a long 4seconds time, the button will "fill with more and more energy" and when I release it, it sent the corresponding "level" of the Bertyzzz pack which is set. 

To finish on this, all normal emojis would be of course accessible in the normal keyboard access and txt input part. So the button is not here to give access to all Unicode emojis.

I imagined this experience could be "creative" and the idea was precisely to think "out" of all others apps standards, and explore a brand new way, with some old school reference (like Wizzz! for example) ^^ 

Thanks to your opinion and inputs, I'll explore ways to have a more standard  UX (probably a grid view of options) ready for upcoming versions! 👍

**Comment by zxxma** [comment]
New proposal for the Menu Design : 

_(Just a note: Logo for Bertyzz is currently not in plain color until this feature is not ready. And not grey, because it give some joyful in the menu, even with a 60% opacity only)_

___
# V3 - Files Menu in App 
### Gallery Open & Selected Pics (with New Menu)
![Preview-Gallery-SelectedPics](https://user-images.githubusercontent.com/37345040/100528247-dcaeb200-31da-11eb-9a3c-36c2bad37554.png)
___
### Choose a GIF  - (Scroll activated in Search)
![GIF](https://user-images.githubusercontent.com/37345040/100528248-dd474880-31da-11eb-8957-dd39dbff302d.png)

### Preview After Record - Audio Files before validation
![Preview-AfterRecord-v2](https://user-images.githubusercontent.com/37345040/100528251-dddfdf00-31da-11eb-9da5-cc108abacf14.png)
___
### After AudioRecord - AudioFile validated
![Preview-AfterRecord-v2-selected](https://user-images.githubusercontent.com/37345040/100528250-dd474880-31da-11eb-8971-9f59832aad79.png)
___
### Security Access - Microphone
![SecurityAccess-Microphone](https://user-images.githubusercontent.com/37345040/100528244-dc161b80-31da-11eb-962f-0e6d7d1b8b0e.png)
___
### Security Access - Gallery 
![SecurityAccess-Gallery](https://user-images.githubusercontent.com/37345040/100528246-dcaeb200-31da-11eb-9738-ebd553334217.png)

**Comment by n0izn0iz** [comment]
done in kaban

**Comment by mp3butcher** [comment]
Hi, I'm using lastest Berty v2.470.3, and the attachment feature is not present.
May the issue should be reopened somehow....?

**Comment by jefft0** [comment]
We don't have plans for the time being to support file attachments in Berty.
