### ISSUE TITLE
Recording Sound Mode in conversation (UX)

### ISSUE THREAD

**Issue by zxxma** [berty/berty#2789]
### Here you'll find the behavior when the user click on "Record a sound message".

This button will have two types of behavior : 
- Keep the button pressed to record. (the most common used behavior)
- Double Tap the button to launch the record, then tape again to stop the record. (can be useful for someone who will record a very long meeting, or a situation where he cannot keep fingers on the phone.)

![RECORDING-1](https://user-images.githubusercontent.com/37345040/99946169-3562f280-2d76-11eb-8f91-dbbfda2aa504.png)

Edit : Preview when record is finished, before send it.

![Preview-AfterRecord](https://user-images.githubusercontent.com/37345040/100254855-19607c00-2f43-11eb-944c-14785880cd64.png)

**Comment by sakul-budhathoki** [comment]
Closed by https://github.com/berty/berty/pull/2926
