### ISSUE TITLE
Jumping KeyboardAvoidingView children in OneToOne.tsx and MultiMember.tsx

### ISSUE THREAD

**Issue by clegirar** [berty/berty#2875]
With @n0izn0iz we spent a day on an issue https://streamable.com/l9040q
In the video you can see the footer is "jumping" when sending a message

After some time we came up with a minimalist version, we change 2 files:
`OneToOne.tsx` where we minimalize 2 components, the `OneToOne` and `MessageList`:
```jsx
const MessageList: React.FC<{ convPk: string }> = ({ convPk }) => {
	const ctx: any = useMsgrContext()
	const conv = ctx.conversations[convPk]
	const messages = useSortedConvInteractions(convPk).filter(
		(msg) =>
			msg.type === beapi.messenger.AppMessage.Type.TypeUserMessage
	)

	const items: any = () => {
		return messages?.reverse() || []
	}

	const renderItem: SectionListRenderItem<any> = ({ item, index }) => {
		return (
			<Message
				id={item?.cid || `${index}`}
				convKind={beapi.messenger.Conversation.Type.ContactType}
				convPK={conv.publicKey}
				previousMessageId={index < items.length - 1 ? items[index + 1]?.cid : ''}
				nextMessageId={index > 0 ? items[index - 1]?.cid : ''}
			/>
		)
	}

	return (
		<ScrollView>{messages.reverse().map((m, i) => renderItem({ item: m, index: i }))}</ScrollView>
	)
}

export const OneToOne: React.FC<ScreenProps.Chat.OneToOne> = ({ route: { params } }) => {
	return (
		<>
			<KeyboardAvoidingView
				style={{ flex: 1 }}
				behavior='padding'
			>
				<MessageList convPk={params?.convId} scrollToMessage={params?.scrollToMessage || '0'} />
				<ChatFooter
					convPk={params?.convId}
				/>
			</KeyboardAvoidingView>
			<ChatHeader convPk={params?.convId || ''} />
			{/* one of us tried everything without ChatHeader so we don't think it changes anything to remove it, we keep it because it's easier to test with it */}
		</>
	)
}
```
and `ChatFooter` in `Chat.tsx`:
```jsx
export const ChatFooter: React.FC<{ convPk: string }> = ({ convPk }) => {
        console.log("footer render")
	const ctx: any = useMsgrContext()

	const usermsg = { body: 'Hello World!', sentDate: Date.now() }
	const buf = beapi.messenger.AppMessage.UserMessage.encode(usermsg).finish()

	const conversation = ctx.conversations[convPk]

	// TODO: Debug, error on restarting node
	const handleSend = React.useCallback(() => {
		ctx.client
			?.interact({
				conversationPublicKey: convPk,
				type: beapi.messenger.AppMessage.Type.TypeUserMessage,
				payload: buf,
			})
			.then(() => {
				playSound('messageSent')
			})
			.catch((e: any) => {
				console.warn('e sending message:', e)
			})
	}, [convPk, ctx.client, buf])

	return (
		<View  style={{height: 100}}>
                    <TextInput/>
                    <Button onPress={handlePressSend} title="send"/>
		</View>
	)
}
```

So you can copy that and reproduce this issue

The bug happens when the keyboard is open and the footer is rerendered

We investigated some points:
- At the beginning, we thought that it was the `SectionList` so we removed it and replaced it by a `ScrollView` with a simple map
- After, we dug the `TextInput` props, maybe a problem with some props badly sets or something but we removed all props and let only essential props and the problem persist
- We also dig the `KeyboardAvoidingView` props, but without success
- When we started digging the implementation of `KeyboardAvoidingView`, we were already tired and gave up (not that the implem is bad, but it was a signal)

Possibly related issue: https://github.com/facebook/react-native/issues/27994

We wrote an hackmd, you can add as you want 👍 https://hackmd.io/s96Z6CtdSEuxS392huCHbw

**Comment by sakul-budhathoki** [comment]
I used `https://www.npmjs.com/package/react-native-keyboard-avoiding-scroll-view`. It also didn't help.

I have been able to fix jumping of input field as below, still not working as expected. I am working on it.

Had to modify 
`react-native/Libraries/Components/Keyboard/KeyboardAvoidingView.js`
Commented below code 
  ```
if (duration && easing) {
      LayoutAnimation.configureNext({
        // We have to pass the duration equal to minimal accepted duration defined here: RCTLayoutAnimation.m
        duration: duration > 10 ? duration : 10,
        update: {
          duration: duration > 10 ? duration : 10,
          type: LayoutAnimation.Types[easing] || 'keyboard',
        },
      });
    }
```

![Screen Recording 2020-12-15 at 5 48 13 PM](https://user-images.githubusercontent.com/13379067/102213066-48448f00-3efe-11eb-9f9a-9c3bc2f4b517.gif)
