### ISSUE TITLE
Where is android BLE driver?

### ISSUE THREAD

**Issue by naiba** [berty/berty#2944]
Hi there, our team wants to use the berty protocol to make a p2p application with n-to-m binary messaging.
I only saw Darwin's BLE driver, is it not available on Android? Or even if there is an Android driver, it can’t be conveniently used as a simple n-to-m p2p application for binary messaging?

Hope to get your answer, thanks.

**Comment by D4ryl00** [comment]
Hi @naiba
We're currently working on Android BLE driver. There are still bugs to fix before we can release it.
I hope it will be released quickly.
Stay tuned :)

**Comment by TheoXD** [comment]
I asked about this on discord the other day, I got this PR link https://github.com/berty/berty/pull/2729 so you can subscribe and get notified when it's ready.

**Comment by naiba** [comment]
> I asked about this on discord the other day, I got this PR link #2729 so you can subscribe and get notified when it's ready.

Great job, I've subscribed.
