### ISSUE TITLE
Add Briar to the comparison matrix

### ISSUE THREAD

**Issue by maverick74** [berty/berty#3038]
Hi there.

Just found out about Berty.

I was going thru the FAQ and analysing your matrix and I noticed the absence of Briar (briarproject.org)

Could you please add it?
I would like to know the advantages of Berty over it.

Thank you

**Comment by link2xt** [comment]
You can open a PR to https://github.com/berty/www.berty.tech, see my PR for example https://github.com/berty/www.berty.tech/pull/224

**Comment by pierreboc** [comment]
Added -> https://github.com/berty/www.berty.tech/pull/231 

Thanks for your input :)

**Comment by maverick74** [comment]
@pierreboc is it me or is there is now many columns repeated?!

also... i thought that briar was distributed and i don't remember being asked my phone number when i tried it... 
but i may not be recalling it right...
