### ISSUE TITLE
Multi accounts and device sync

### ISSUE THREAD

**Issue by guestisp** [berty/berty#3157]
Hi,
two questions:

1) berty supports a multiple account config? Like using two accounts on the same devices (telegram, in example)
2) is possible to sync contacts and messages on multiple devices ? (in example, the same account shared on my mobile phone, my desktop, my tablet and so on)

tnx

**Comment by zxxma** [comment]
Hi 👋 
1. yes, this feature is already built.
2. soon™️ yes, not now.

Thanks for questions, it will be added to FAQ on website soon.

**Comment by guestisp** [comment]
Tnx.
Do you have an ETA for sync ? 1 month, 10 months....

**Comment by zxxma** [comment]
I personally would say few months, cannot give more details for the moment, sorry

**Comment by xxxserxxx** [comment]
Is this still in the roadmap (device sync)?
