### ISSUE TITLE
Textbar not visible because its under the keyboard.

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#3161]
When I want to type anything, the keyboard goes up like normal and the box with my text goes with it, but after a second or 2 the text box goes down under the keyboard and I can't see what I'm typing anymore. Shown in video.

https://user-images.githubusercontent.com/38732192/111194362-6aac7e00-85bb-11eb-938b-30fe4ab063b5.mp4

**Comment by sakul-budhathoki** [comment]
Hi @LFGaming . I couldn't reproduce above issue on these two simulators.

![Screen Shot 2021-03-16 at 3 53 02 PM](https://user-images.githubusercontent.com/13379067/111291990-d4865f80-866f-11eb-8576-0c814779b62a.png)

Can you share me details of the device you are testing?
Thank you.

**Comment by LFGaming** [comment]
Hi, this is the one I'm using, and also the (pretty sure latest) android studio canary build. if you need more let me know

![studio64_2021-03-16_12-03-14](https://user-images.githubusercontent.com/38732192/111298897-9bd68e00-864f-11eb-905f-f73f8ac18600.png)
