### ISSUE TITLE
How do I install Berty on cPanel?

### ISSUE THREAD

**Issue by ShreyaanVashishtha** [berty/berty#3241]
Is there any way for me to install Berty on cPanel hosted website?

**Comment by ShreyaanVashishtha** [comment]
Does anyone know?

**Comment by aeddi** [comment]
Hi @ShreyaanVashishtha,
There is no package of Berty provided for cPanel.
You can always install Berty on your server using SSH but it's still too early, I recommend you to wait until there is precise documentation on the subject unless you really know what you are doing.
