### ISSUE TITLE
Linux AppImage or Flatpak

### ISSUE THREAD

**Issue by snakyjake1** [berty/berty#3352]
Might there be a Linux AppImage or Flatpak?

**Comment by aeddi** [comment]
Hello, why not?
Maybe a community member could take care of building it... :)

**Comment by blackPantherOS** [comment]
We can build an AppImage and RPM package as well from berty binary or source, but it doesn't make much sense now without avalilable any user friendly gui

**Comment by jefft0** [comment]
The Berty team doesn't have plans right now to create Linux package manager distributions, but we encourage the community to create them. If the time comes when you work on creating a package, please open a new issue. Closing this issue.
