### ISSUE TITLE
[FEATURE]: < Android version>

### ISSUE THREAD

**Issue by zanezha0** [berty/berty#3364]
## Possible Implementation

When will the Android version come out？

**Comment by LFGaming** [comment]
You can join the Beta in the [Discord](https://crpt.fyi/berty-discord), in the secret door channel, there is no time estimate yet for when the full  release. But you can freely join the beta in  the discord at this moment in time.

**Comment by LFGaming** [comment]
There is also [this form](https://airtable.com/shr0s1TKHPPRQQbAK) in which you can ask for a early acces, but I don't know how quick that one is. But you don't need a discord account for it.
