### ISSUE TITLE
[BUG]: QR code scan even when popup is there

### ISSUE THREAD

**Issue by KristofKekesi** [berty/berty#3393]
### Actual Results / Problem

When I'm scanning a QR code to join a group with an invalid QR (edit: also with a valid QR)  the popup will show up, but the program is still looking for QRs. It wouldn't be noticable if my phone wasn't shaking.

### Expected Results / Possible Fix

Don't scan for QR if popup is there.

### Give use some context

![198164834_860393541221668_4581254370981712286_n](https://user-images.githubusercontent.com/64812024/122841076-b29a1a00-d2fb-11eb-94fc-1828df8a9e08.jpg)

### If you are running on mobile, what's your version/branch? what's your device and OS?
I'm on iOS 14.7 (29G5023c) with an iPhone 11, The version of Berty is 2.42.1.3.

### Anything else you want to tell us, like your favorite cheese?
Well if you ask :D it is  mozarella.

**Comment by aeddi** [comment]
Hello, thanks for your input! 👍 
We'll look into it and we'll update this issue when it's fixed.
