### ISSUE TITLE
Inconsistency with -log.file flag

### ISSUE THREAD

**Issue by mathisve** [berty/berty#3398]
When using the -log.file flag like this using the `rdvp serve` command, everything works fine.
```bash
rdvp serve \
	-log.format=json \
	-log.file=/home/ec2-user/log.json
```

But when you try to use the same flag on `berty daemon`, it complains about it not being a directory.
```bash
berty daemon \
	-log.format=json \
	-log.file=/home/ec2-user/log.json
error: TODO(#666): TODO(#666): TODO(#666): mkdir /home/ec2-user/log.json: not a directory:
    berty.tech/berty/v2/go/internal/initutil.(*Manager).getLogger
        /home/mathis/Downloads/berty/go/internal/initutil/logger.go:85
#1:
    berty.tech/berty/v2/go/internal/logutil.NewLogger
        /home/mathis/Downloads/berty/go/internal/logutil/logutil.go:132
#2:
    berty.tech/berty/v2/go/internal/logutil.newFileWriteCloser
        /home/mathis/Downloads/berty/go/internal/logutil/file.go:43
```
If you run the above command with `-log.file=/home/ec2-user/`, it works perfectly fine. 
So i'm guessing it's just an inconsistency in the flags requiring either a directory or a file. Maybe it should be renamed to `-log.dir` or something similar.

I have tested it out on all the infra types and the commands that require a directory are the following: `berty daemon`, `berty repl-server` and `berty token-server`. 
The only one that is ok with a file as input is `rdvp serve`

**Comment by moul** [comment]
yep, we recently switched the behavior of cli flogs on the main berty binary, but the other binaries (rdvp, relays, etc) are still using the old format

I'll give a look soon, in the meantime, yes you should keep  in mind that the behavior is not consistent

**Comment by jefft0** [comment]
Hello @mathisve . We are reviewing old issues. Is this still relevant?

**Comment by jefft0** [comment]
Close as inactive.
