### ISSUE TITLE
Thoughts on criminal usage?

### ISSUE THREAD

**Issue by jilleJr** [berty/berty#3421]
Hello! I'm really fond of what you produce here with Berty and I really want to see it become the greatest messaging app that it has the potential of.

The technology is before it's time, mostly regarding politicians and the police who are not really caught up with the cutting edge stuff such as this new wave of p2p tech of libp2p and IPFS.

Question is: have you considered the application of Berty within criminal circles? And do you plan on any counter-measures?

WhatsApp transitioning away from E2EE was a big strike in the war for privacy, as with the story of many other messaging apps. We don't want big tech companies mining data from our personal lives just for some quick cash, but we shouldn't want to make it harder for the police with every new toy that comes out.

Some people have a war against their government, where Berty could be a really helpful tool to unify the people and counteract censoring. While I live in a highly privileged country where I have no objection in my government snooping around, where tools like Berty could do more damage than good.

Many of your blog posts (example: <https://berty.tech/blog/future-of-berty/>) talk about Berty as a tool to fight private corporations and governments. In my mind, fighting corporations, fine; but fighting governments by creating tools to go behind their backs instead of trying to work with them sounds backwards to me.

---

To be clear, I'm not asking you to shut down or anything like that. I'm just asking if you've thought about it and at least considered the damage an app like Berty could do to the war against drugs, human trafficking, et.c

The technology is amazing. The fact that the police is falling behind tech-wise is not a good argument for haulting. Of course this world could be better off with tech like Berty, but it feels like we're walking a fine line here.

Thoughts?

**Comment by zxxma** [comment]
Hey @jilleJr 👋 
Thanks for opening this issue, you created the opportunity to express ourself on this important topic.
We'll reply with an official blogpost in upcoming days!

**Comment by jilleJr** [comment]
I just now noticed your blog post <https://berty.tech/blog/liberty-vs-safety/>. Wonderfully well written! Big fan of that Amnesty quote :heart: 

I still find one of my points unresolved:

> /.../ fighting governments by creating tools to go behind their backs instead of trying to work with them sounds backwards to me.

But what I understood from the blog post is that Berty Tech is leaning more on the argument that "it's not our fault that police and polititians are out-of-date" and heavily on the "security means nothing if it requires giving up freedom" argument.

I get that point of view, and I accept that reasoning. Glad you took the time to write that blog post and clear up your standing on this topic. Personally I'm more attracted by Berty now, even though you don't have 100% the same reasoning as me, but because you can take a stand behind an argument.

Great work! I'm closing this issue as I find my question resolved.
