### ISSUE TITLE
Navigate instead of erroring on contact already added

### ISSUE THREAD

**Issue by n0izn0iz** [berty/berty#3451]
When a contact is already added, open the contact profile or the existing conversation

The error check is done here: https://github.com/berty/berty/blob/097eb0229f22e2abce3addd750c8dce98e92845f/js/packages/components/modals/InvalidScan.tsx#L126

We shouldn't show the invalid scan modal but navigate instead

**Comment by vaniisgh** [comment]
hey!
I am a newbie to Bertie :) would it be ok if i tried fixing this

**Comment by n0izn0iz** [comment]
Hello, sure go for it :)
Feel free to ask questions on the #devroom channel in our [discord](https://crpt.fyi/berty-discord)  ;)
