### ISSUE TITLE
[BUG]: Crash when updating profile picture

### ISSUE THREAD

**Issue by vuldin** [berty/berty#3735]
### Actual Results / Problem

The first task the app gives me to compkete my profile is to update my profile picture:
![Screenshot_20211206-091921_Berty Yolo.jpg](https://user-images.githubusercontent.com/310946/144862583-a4839998-1dc3-489e-8476-53b9e4006a36.jpg)

I open my profile and click my picture to update:
![Screenshot_20211206-091943_Berty Yolo.jpg](https://user-images.githubusercontent.com/310946/144862699-ff343ca7-2cab-4904-aea5-566e8f7a966a.jpg)

Then once I choose an image from the gallery the app crashes:
![Screenshot_20211206-092006_One UI Home.jpg](https://user-images.githubusercontent.com/310946/144862778-cfa46321-5400-454e-9950-775359522439.jpg)

### Expected Results / Possible Fix

I expect the app to update my profile picture.

Device: Samsung Galaxy A71 5G
OS: see screenshot below
![Screenshot_20211206-092637_Settings.jpg](https://user-images.githubusercontent.com/310946/144863423-4898bd73-0a0a-4394-af93-6be1eb20a28a.jpg)

**Comment by D4ryl00** [comment]
Hello, thanks for your report.
This is fixed by https://github.com/berty/berty/pull/3765.

**Comment by vuldin** [comment]
Awesome thanks!
