### ISSUE TITLE
What about using `created_at` as unique ID for the UI?

### ISSUE THREAD

**Issue by moul** [berty/berty#387]
instead of having rules for like `{type}:{author_id}:{event_id}` for events, `{type}:{id}` for other entities, maybe we can always use the created_at event as primary key in the nodeapi, we will still use the existing IDs for p2papi, but for the UI that heavily uses caching etc, it may make things easier to use

what do you think?

**Comment by jefft0** [comment]
Closed on Oct 15, 2018 as won't fix.
