### ISSUE TITLE
Cannot enable/disable bluetooth transport

### ISSUE THREAD

**Issue by lucy2812** [berty/berty#4020]
### Problem

On Apple iOS, I cannot re-enable Berty's Bluetooth Network after disabling Berty's Bluetooth.

When trying to enable Berty's Bluetooth Network, I get a popup asking to grant permissions to Berty.  I select "Allow", but nothing happens.

Similar for any option that uses Bluetooth (Off-Grid Communication, Multipeer Connectivity.

### Version

The app doesn't inform the user the Berty version in About Berty.  But the Apple App Store says this is version 2.358.1.

**Comment by clegirar** [comment]
Hi

**Comment by jefft0** [comment]
Closing as inactive/resolved.
