### ISSUE TITLE
Packaging for multi user

### ISSUE THREAD

**Issue by RubenKelevra** [berty/berty#4114]
I'm the current package maintainer for ArchLinux's AUR package and was wondering what's the best practice is to install the protocol/messenger/GUI on a system:

- Do I better run the Berty daemon once on a system as a dedicated user, or once per regular user?
- Can I connect Berty to an already running IPFS daemon?
- Should the daemon start on login (as it's low footprint and needs time to find the network) or should I start it on demand when the GUI tries to connect to the port?

Thanks!

**Comment by jefft0** [comment]
Hello @RubenKelevra . We are reviewing older open issues. This is an interesting question. Are you still working on this project?

**Comment by jefft0** [comment]
Closing as inactive.
