### ISSUE TITLE
App crash when multiples clicks on profile name

### ISSUE THREAD

**Issue by saivishwak** [berty/berty#4149]
### Actual Results / Problem

Steps to reproduce:
Click on the top profile avatar
then click on the profile name several times the app crashes on android.

### Expected Results / Possible Fix
The app should not crash on several clicks

If you are running on mobile, what's your version/branch? what's your device and OS?
Android 12 - latest download (approximately 30 mins before raising this issue)

**Comment by jefft0** [comment]
I confirm this bug on my phone (Samsung S20, Android 12).

**Comment by jefft0** [comment]
We are aware of this crash in the UI. A fix is in progress to fix it.

**Comment by peletron** [comment]
Moving issue to @4222 since we have new bug template there.
