### ISSUE TITLE
Open profile edit dialog and swipe right to go back the dialog still stays

### ISSUE THREAD

**Issue by saivishwak** [berty/berty#4151]
### Actual Results / Problem

Open profile edit dialog and swipe right to go back the dialog still stays

### Expected Results / Possible Fix

the dialog should disappear. This works fine when the back arrow is used but not with the swipe right.

If you are running on mobile, what's your version/branch? what's your device and OS?

Android 12
![Screenshot_20220523-221102_Berty](https://user-images.githubusercontent.com/55258956/169869279-949c12d2-c579-4d13-9f5a-91efbc16a6cd.jpeg)

**Comment by peletron** [comment]
@saivishwak I checked this issue on Android 12 ( Samsung s21+ ) using latest available version and all is good for me? 
Can you please recheck this issue on latest version using your device?

**Comment by peletron** [comment]
Issue doesn't exist anymore. Tested on multiple android and iOS devices.
