### ISSUE TITLE
App crashes in settings

### ISSUE THREAD

**Issue by peletron** [berty/berty#4222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

V# 2.391.3

### OS

Android

### OS version

Android 12

### Device

Samsung Galaxy S21+ 

### Steps to reproduce

1. Open the app 
2. Open settings via the users icon 
3. Double click on the users name 

### Current behavior

App crashes if the user clicks on the user's names.

### Expected behavior

App should not crash no matter what.

### Other

See the attached video on this link for more information
https://drive.google.com/file/d/1u0Y45XkYykXrj36ANysPxGMudvCQId94/view?usp=sharing

**Comment by LFGaming** [comment]
Duplicate of issue #4149 ?

**Comment by peletron** [comment]
@LFGaming , yes. Let's switch issue to this ticket since we have new bug template here.

**Comment by aeddi** [comment]
Should be fixed by https://github.com/berty/berty/pull/4274

**Comment by peletron** [comment]
Issue fixed. 
Tested on #4274 Berty YOLO
