### ISSUE TITLE
Picture upload doesn't work at first try

### ISSUE THREAD

**Issue by peletron** [berty/berty#4225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

V# 2.391.3

### OS

Android

### OS version

Android 12

### Device

Samsung Galaxy S21+ 

### Steps to reproduce

1. Open app 
2. Open any group 
3. Click on the group icon 
4. Click on picture

### Current behavior

Selecting, cropping and applying a picture doesn't upload it, a user has to repeat this action twice in order to update the picture. Make sure you clear a cache of app or have fresh install in order to replicate this issue.

### Expected behavior

User should be able to upload a picture on the first try.

### Other

See the attached media for more information
https://drive.google.com/file/d/1PWNtzeWdZbvDGCFcM7bMTMWQrxkYQyTs/view?usp=sharing

**Comment by LFGaming** [comment]
For me it updates the picture once I leave the group setting menu (so there where you see the we code and the members etc) does it also not update for you then?

**Comment by peletron** [comment]
After more investigation, I replicate this issue on multiple iOS and Android devices.

**Comment by clegirar** [comment]
Hi 👋
After trying couple of times to reproduce the issue, i didn't success..
Can you please send a video of the behavior you have ? 🙂

**Comment by clegirar** [comment]
Thanks 👍 I'll dig, i'll keep you informed 👍

**Comment by peletron** [comment]
Fixed and tested in #4393. Waiting for release
