### ISSUE TITLE
Search placeholder is cut off

### ISSUE THREAD

**Issue by peletron** [berty/berty#4226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

V# 2.391.3

### OS

Android

### OS version

Android 12

### Device

Samsung Galaxy S21+ 

### Steps to reproduce

1. Open the app
2. Review search field place holder

### Current behavior

In Search field placeholder is cut off, missing d at the end. Currently it's written "Search keywor"

### Expected behavior

It should be "Search keyword"

### Other

Take a look at the attached media for more information
https://drive.google.com/file/d/17WoCp3eXDHoa-xFRU3anNPPouof5eOM-/view?usp=sharing

**Comment by LFGaming** [comment]
It's not misspelled, it has the d but for your phone it is apparently cut off, so still a big but a bit different than described :)

**Comment by peletron** [comment]
@LFGaming, that is correct. Addressing this issue for the fix.

**Comment by peletron** [comment]
Tested on Berty Yolo #4274 
Fixed issue.
Placeholder is fully visible
