### ISSUE TITLE
App crashes when pressing the + for files

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

v2.391.3

### OS

Android

### OS version

Android 12

### Device

Samsung galaxy S20 5G

### Steps to reproduce

1. Go to any chat.
2. Press the `+` button on the left of the text bar.
3. The app crashes very often when pressing (but not always).

https://user-images.githubusercontent.com/38732192/176301898-d5f97b0c-5bac-438b-b166-8f5c684a8f04.mp4

### Current behavior

The app crashes very often when pressing the `+` button.

### Expected behavior

The app should not crash when pressing the `+` button.

**Comment by jefft0** [comment]
Hello @LFGaming . Is this a new crash behavior with the latest release? Was it working on your phone with an earlier version?

**Comment by LFGaming** [comment]
> Hello @LFGaming . Is this a new crash behavior with the latest release? Was it working on your phone with an earlier version?

I have no idea,, I'll test it with some older Yolo versions once I'm back home.

**Comment by jefft0** [comment]
Hello @LFGaming . I just happen to have the same phone as you (Samsung S20 with Android 12.) I confirm the bug you are seeing. After pressing + the third time, the app crashes.

**Comment by LFGaming** [comment]
> Hello @LFGaming . I just happen to have the same phone as you (Samsung S20 with Android 12.) I confirm the bug you are seeing. After pressing + the third time, the app crashes. (This is with the latest update v2.391.3 from the Play Store.)

For me it's not necessary the third tap, but good to know it not just me :)

**Comment by jefft0** [comment]
We are aware of this crash in the UI. A fix is in progress to fix it.

**Comment by peletron** [comment]
Confirming issue on Samsung s21+ and Samsung s22 Ultra. Tested on iPhone 13 Pro Max and iPhone 12 Pro Max and all good on iOS. Version: v2.391.3

**Comment by peletron** [comment]
Bug is fixed on https://github.com/berty/berty/pull/4274 (Berty YOLO)
Tested and approved. Waiting for release
