### ISSUE TITLE
Add file in chat crashes app

### ISSUE THREAD

**Issue by peletron** [berty/berty#4244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

12

### Device

Samsung Galaxy S21+

### Steps to reproduce

1. Open app 
2. Open any chat 
3. Click on plus icon in lower left corner multiple times

### Current behavior

App will often crash when user clicks once or double clicks on this icon (Not always, but often)
see video on following link
https://drive.google.com/file/d/1mdQ5PfF8ICJ7-tal1RPj-zuJ05zTqpiO/view?usp=sharing

### Expected behavior

App shouldn't crash

**Comment by aeddi** [comment]
Should be fixed by https://github.com/berty/berty/pull/4274

**Comment by peletron** [comment]
Issue can't be replicated anymore. 
Tested on #4274 Berty YOLO
