### ISSUE TITLE
Name changed in the app do not update in Accounts list 

### ISSUE THREAD

**Issue by peletron** [berty/berty#4248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

Android 12 / iOS 15.5

### Device

Samsung Galaxy S21+ / Iphone 13 Max Pro

### Steps to reproduce

1. Open app 
2. Open settings via users icon 
3. Click on users name  
4. Change name 
5. Accounts 
6. Accounts dropdown menu

### Current behavior

After user changed name in settings this new name isn't updated in Settings -> Accounts -> Accounts dropdown menu.
In Accounts dropdown menu only names which user assigned while creating new profile are shown

See video attached on link below
https://drive.google.com/file/d/1P7bPFOXkOa1Ti-2jQ0bqWyAelaxF0Wdg/view?usp=sharing

### Expected behavior

Once name is updated in settings, these changes should also be updated

**Comment by clegirar** [comment]
Hi, multi-account is not maintain anymore, you can play with this feature in the devtools 👍
