### ISSUE TITLE
User is unable to open Open source licenses

### ISSUE THREAD

**Issue by peletron** [berty/berty#4257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

12

### Device

Samsung Galaxy S21+

### Steps to reproduce

1. Open app 
2. Open settings via users icon 
3. Click on About Berty  
4. Click on Open Source Licenses

### Current behavior

User is unable to open Open source licenses. After clicking on Open Sources Licenses nothing happens

see attached video
https://drive.google.com/file/d/1GGgGBN71RNIS9IiFi0n4l7OJaqXONz-y/view?usp=sharing

### Expected behavior

User should be asked Web content permission and be navigated to Open Sources Licenses page

**Comment by LFGaming** [comment]
I indeed also have this bug on my iPhone, I have reported it somewhere but can't find where so good to see you made this report too :)

**Comment by jefft0** [comment]
@iuricmp will make this button show a copy of the license from the repo:
https://github.com/berty/berty/blob/master/LICENSE-APACHE

**Comment by jefft0** [comment]
@iuricmp still working on it.
