### ISSUE TITLE
User is unable to generate new themes while Dark-theme is selected

### ISSUE THREAD

**Issue by peletron** [berty/berty#4258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

12

### Device

Samsung Galaxy S21+

### Steps to reproduce

1. Open app 
2. Open settings via users icon 
3. Click on Appearance
4. Click on Theme Editor
5. Select Dark theme
6. Click Generate theme

### Current behavior

When Dark theme is selected clicking on Generate theme button shows no results and theme remains dark

### Expected behavior

In all other cases, when every other default theme is selected user is able to generate new theme and dropdown will automatically change selection to current-generated with new theme applied except in case of Dark-theme 
see attached video
https://drive.google.com/file/d/1GGgGBN71RNIS9IiFi0n4l7OJaqXONz-y/view?usp=sharing

**Comment by clegirar** [comment]
Hi, themes are a development tool now, it's not a priority for the moment to support theme 👍
