### ISSUE TITLE
Chat: All files in documents section has same upload time

### ISSUE THREAD

**Issue by peletron** [berty/berty#4273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

iOS

### OS version

iOS 15.5

### Device

iPhone 13 Max Pro / iPhone 12 Max Pro

### Steps to reproduce

1. Open Berty app at Phone A 
2. Open Berty app at Phone B
3. Connect two phones through Berty message
4. Send Voice message from Phone A to Phone B 
5. Send File from Phone A to Phone B 
6. Open conversation at Phone B 
7. Click on the User image at top right corner
8. Click on the Media, links & docs 
9. Switch to Documents tab

### Current behavior

All files/documents under document section has same upload time. It is 01:00 AM.
https://i.imgur.com/3G1O2o4.png

### Expected behavior

I am expecting to see exact upload time of that voice message/file that is sent through chats,. There shouldn't be default ones

**Comment by clegirar** [comment]
Hi, we deleted some non essentials features, like send medias, to be focus on the most important ones 👍
