### ISSUE TITLE
Android: App crash when user try to react on some message

### ISSUE THREAD

**Issue by peletron** [berty/berty#4282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.396.3

### OS

iOS

### OS version

iOS 15.5

### Device

iPhone 13 Max Pro

### Steps to reproduce

1. Open Berty app
2. Open conversation with some user
3. Find some message that you received
4. Tap and hold on that message

### Current behavior

App crashed after user try to add react on some message. 

https://user-images.githubusercontent.com/105677764/179022249-b434a6a1-237e-4020-a878-c1ad1f901550.mp4

### Expected behavior

After long tap we should show reaction bar and user should be able to add reaction to the message

**Comment by aeddi** [comment]
Should be fixed by #4274

**Comment by peletron** [comment]
App is not crashing anymore, but still there is issue reported in https://github.com/berty/berty/issues/4275.


Tested on build https://github.com/berty/berty/pull/4274. Pending release

**Comment by peletron** [comment]
@clegirar That is correct. No app crash anymore :)
