### ISSUE TITLE
Chat: Voice message elements are cut off on android

### ISSUE THREAD

**Issue by peletron** [berty/berty#4289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

Android 12 

### Device

Samsung Galaxy S21+

### Steps to reproduce

1. Open the app;
2. Choose any conversations;
3. Send a voice message;
4. Take a look at the bottom left part of voice message.

### Current behavior

Voice message element is cut off.

### Expected behavior

Element should not be cut off. Voice messages should look the same on Android as on iOS.

### Other

Android: 
![viber_image_2022-07-17_17-30-47-064](https://user-images.githubusercontent.com/105677764/179405662-6d72f426-93c1-4a37-94f3-35f0bc4cee55.jpg)

iOS for reference: 
![viber_image_2022-07-17_16-13-48-207](https://user-images.githubusercontent.com/105677764/179405671-278dacd9-13ef-48a7-a206-7a41a6e6833e.jpg)

**Comment by peletron** [comment]
Issue has still not been fixed. 
see attached picture as an example
![image](https://user-images.githubusercontent.com/105677764/184428996-c6ccb185-b11e-40a0-8ce3-40190286d6f2.png)


Tested on Berty Yolo #4322 + SAMSUNG GALAXY S21+ // ANDROID 12

**Comment by clegirar** [comment]
Hi, we deleted some non essentials features, like send voice message, to be focus on the most important ones 👍
