### ISSUE TITLE
User can save Theme without a name 

### ISSUE THREAD

**Issue by peletron** [berty/berty#4299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

Android 12 

### Device

Samsung Galaxy S21+

### Steps to reproduce

1. Open app 
2. Open settings via users icon 
3. Click on Appearance 
4. Click on Theme Editor 
5. Generate theme 
6. Save this theme without name

### Current behavior

Actual result: User is able to save theme without a name. Doing this multiple times will overwrite users themes each time and users will lose track of their themes (There is no suggestion theme is overwritten)
see attached video on link below
https://drive.google.com/file/d/1QOzwquSsKFOcUwFICGrrhf8zI5NacFUJ/view

### Expected behavior

User shouldn't be able to save theme without providing theme name

**Comment by clegirar** [comment]
Hi, theme are now a development tool, and development feature are not our priority for the moment 👍 
But if you want to help us with this kind of issues, don't hesitate to ping us on our discord 👍
