### ISSUE TITLE
iOS: Files with long names aren't displayed properly in conversation

### ISSUE THREAD

**Issue by peletron** [berty/berty#4310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

iOS

### OS version

iOs 15.5

### Device

iPhone X 

### Steps to reproduce

1. Log in to app
2. Open converastion
3. Send file with long name

### Current behavior

Names of files aren't fully shown on screen. Part of name is cut of(there is no gap with end of screen) and out of conversation frame. Also timestamp and status(Sent) is cut of from conversation frame 

see pic for additional details
![image](https://user-images.githubusercontent.com/105677764/180325582-6448f26f-b003-4544-b5f4-3cd396aa97c5.png)

**Comment by clegirar** [comment]
Hi, we deleted some non essentials features, like send files, to be focus on the most important ones 👍
