### ISSUE TITLE
Pictures take too long to be received and loaded via Bluetooth

### ISSUE THREAD

**Issue by peletron** [berty/berty#4311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.391.3

### OS

Android

### OS version

Android 12 / iOS 15.5

### Device

Samsung Galaxy S21+ / iPhone X

### Steps to reproduce

1. Log in to app
2. Turn off Wifi+Mobile Data and turn on only bluetooth
3. Send few pictures and files between two phones

### Current behavior

Pictures take way too long time to be received by receive phone.
In my case it took about 3 minutes for receiving phone to acknowledge that photos are sent by sender's phone.
About 6 minutes passed before 1/3 pictures were loaded 

Senders phone message sent 
![image](https://user-images.githubusercontent.com/105677764/180327510-8f15dcfd-b620-4055-bb5a-095913bfce13.png)

Senders phone message few minutes ago
![image](https://user-images.githubusercontent.com/105677764/180327585-d60362be-dfce-4cdf-8fd7-72d88112c36c.png)
Receivers phone message acknowledged after few minutes but not loaded
![image](https://user-images.githubusercontent.com/105677764/180327672-eac5c3c2-922a-43b2-a66d-fb401820cb45.png)

**Comment by x80486** [comment]
Pictures take too long to be received (and sent) using WiFi and (a moderate fast) mobile network as well.

**Comment by clegirar** [comment]
Hi, we deleted some non essentials features, like send pictures, to be focus on the most important ones 👍
