### ISSUE TITLE
Chat: Message is stuck in sending state

### ISSUE THREAD

**Issue by peletron** [berty/berty#4334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.396.3

### OS

iOS

### OS version

iOS 15.5 / Android 12

### Device

iPhone 13 Pro Max / Samsung s21 + 

### Steps to reproduce

1. Open Berty application
2. Start connection with some user 
3. Send some message

### Current behavior

Message is stuck in sending mode and sometimes it takes 20-25 minutes for message to be sent. This issue is more easy to replicate if you are starting your conversation with someone for the first time.

![image](https://user-images.githubusercontent.com/105677764/183088039-ab405fbc-7882-4f46-b70d-eb2c5c637f19.png)

### Expected behavior

Once message is sent and there is not problem with connection message should be sent and received within 10 sec.

### Other

Sometimes in order to resolved this issue, it helps to open conversation on both, sender and receiver phone.

**Comment by peletron** [comment]
@x80486 this is bug and our development team is working on it. Did you try with reopening application when you got this problem?

**Comment by x80486** [comment]
I did reopen the application. I even killed it and open it again. This one in particular is pretty important because it's core to an application of such nature to be able to send and receive reliably.

I will wait for you folks to push a fix and give it a whirl again.

**Comment by x80486** [comment]
I'm not entirely sure if this would be the case for this bug, but I was able to verify that the recipients indeed receive the notification and the message on their end. The status doesn't change on my end until they open up the application, and then I have to close mine in order for that status to be updated.

**Comment by jefft0** [comment]
No more questions. Close as resolved.
