### ISSUE TITLE
User can't scroll trough gallery to choose some older photos

### ISSUE THREAD

**Issue by peletron** [berty/berty#4341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

Berty Yolo V# v2.422.2-dev.12+g / Berty Messenger PROD V#2.391.3
### OS

Android

### OS version

Android 11

### Device

Samsung Galaxy A52s 

### Steps to reproduce

1. Conversation with your contact is open
2. Click on the "Add" (+) button in the bottom left corner
3. Choose the "Gallery" option
4. Try to scroll through the gallery to see older photos

### Current behavior

User can't scroll through the gallery to choose some older photos. 

https://user-images.githubusercontent.com/105677764/183239840-ba4ebec3-9819-4042-a55c-6922313d0972.mp4

### Expected behavior

User should be able to scroll through the gallery.

**Comment by clegirar** [comment]
Hi, we deleted some non essentials features, like send a picture, to be focus on the most important ones 👍
