### ISSUE TITLE
File cannot be downloaded

### ISSUE THREAD

**Issue by peletron** [berty/berty#4342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

Berty Yolo V# v2.422.2-dev.12+g / Berty Messenger PROD V#2.391.3

### OS

Android

### OS version

Android 11

### Device

Samsung Galaxy A52s 

### Steps to reproduce

1. Open conversation
2. Your contact sends you a file
3. Tap on it to download it
4. Wait for the file to be downloaded

### Current behavior

When the user clicks on the file there will be a message displayed next to it "Downloading", but if you wait you'll see that file won't be ever downloaded.

https://user-images.githubusercontent.com/105677764/183240148-c16d0f45-165d-40cb-8495-66a757d80c8b.mp4

### Expected behavior

User should be able to download files.

### Other

Also if you try to download the file that you sent the result will be the same. File would never be downloaded.

![image](https://user-images.githubusercontent.com/105677764/183240217-7b5edc0a-8d6f-406c-8c6e-6dad8e47e09d.png)

**Comment by clegirar** [comment]
Hi, we deleted some non essentials feature, like send a file in a conversation, to be focus on the most important ones 👍
