### ISSUE TITLE
Open in app not working

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

Every version

### OS

iOS

### OS version

iOS 15.5

### Device

iPhone 12 mini

### Steps to reproduce

1. Get a link to the I’d website, example : [This](https://berty.tech/id#contact/oZBLFEH1BLTRoDWdStRaiQsm2PnUxFcmMUcezadSzBWzbP4kTB9DEu8mhk4fg34pogz5am7bms945Muj8hW5yTinuhUKHdn/name=LFGaming) 
2. Get send to the website.
3. Press the button “open in app”
4. You will be send to www.Berty.tech/id#

### Current behavior

https://user-images.githubusercontent.com/38732192/183405767-e1b5a994-4daf-4822-a47a-4683f502ff81.MOV

### Expected behavior

When pressing open in the app, the app should open with the contact there.

**Comment by peletron** [comment]
Hi @LFGaming , thanks for report of this issue. I can replicate issue but only if my link open in browser first, which is usually case when I am opening links in our #qr-sharing channel on Discord. 

Alternative for this is to long press on Open in app button on that website and select Open in Berty option like I did on video: 


https://user-images.githubusercontent.com/105677764/183743335-161052a1-c352-4538-85a9-9fcb0ec03b11.mp4

In meantime, we will take care of the issue.

**Comment by LFGaming** [comment]
Ah okay, thanks. Didn't know about that work around.

**Comment by LFGaming** [comment]
It now not anymore seems to work with holding the `open in the app` button. It does open the app, but it does not give me the account of the person who's link it was

**Comment by jefft0** [comment]
@LFGaming , there were recent commits to fix "deep link" issues. Is this bug resolved?

**Comment by LFGaming** [comment]
> @LFGaming , there were recent commits to fix "deep link" issues. Is this bug resolved?

Just updated my app to 2.468.2 and it seems to work now 👍
