### ISSUE TITLE
berty: cut the url too long

### ISSUE THREAD

**Issue by MikaelVallenet** [berty/berty#4360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

CLI tools (berty mini, daemon, etc.)
iOS application

### Berty product version

berty-mini: 2.428.0
berty messenger: 4345

### OS

Linux
IOS

### OS version

Ubuntu 22.04 LTS
iOS 15.6

### Device

PC
iPhone 13

### Steps to reproduce

Send a long to a user which use Berty

### Current behavior

The user could not be use this link bc the link is cut.
In fact it is interesting to cut it in the front for the display, but if you click on it you are redirected to the cut link
The main problem with this is that we are redirected to a link that is not the one that our interlocutor shares with us

Example : 

![image](https://user-images.githubusercontent.com/71339153/184167689-3b738e37-d792-4a99-848d-8c6339b522e0.png)

if I click on these links which are group invitations, it redirects me to a friend invitation of a random person? nothing to do with the link

### Expected behavior

The link should be cut only visually, but if you click on it you should be redirected to the whole link

**Comment by peletron** [comment]
@Mikatech thanks for reporting this issue. Our dev team will take a look as soon as possible!

**Comment by jefft0** [comment]
@jefft0 to take a look.

**Comment by MikaelVallenet** [comment]
> Hello @MikaelVallenet . I am trying to reproduce your issue. In Berty mini, yes the displayed URL is cut short. If the Terminal automatically turns it into a clickable URL, then yes the URL is cut short. But the URL is also copied to the clipboard. In Berty mini, if I enter `/group share` it prints:
> 
> ```
> 16:58:17 -------- https://berty.tech/id#group/8ejngpAxnMPuFgC23JetZTTu2E3htHPbGaLHsSEj84Fn1WonMP5akWLbBoWvx61MicSNmVv7vSf…
> 16:58:17 -------- (Copied to clipboard)
> ```
> 
> The full URL is in the clipboard. Does this work for you?

Hi jefft0, i don't have the setup ready to test but seem's like i did not have that when i did it.
Perhaps this feature was'nt yet release when i had my problem. However i think it would be better to handle the URL to not redirect to unknown location because it is cut.

**Comment by jefft0** [comment]
I believe that the URL link is created by the terminal program based on the visible text. Is that right? I don't think that Berty mini can override the terminal program.

**Comment by MikaelVallenet** [comment]
> I believe that the URL link is created by the terminal program based on the visible text. Is that right? I don't think that Berty mini can override the terminal program.

Perhaps, if we can't fix it it's OK since the URL is copied to clipboard :+1:

**Comment by jefft0** [comment]
OK. Thanks for the feedback. Closing as issue has a workaround.
