### ISSUE TITLE
Title for an invite site is Pierre

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.429.2-dev

### OS

iOS

### OS version

iOS 15.5

### Device

iPhone 12 mini

### Steps to reproduce

1. Make a group chat
2. Click on the invite by link button
3. The link you’ll get says Pierre invites you.

### Current behavior

The link says Pierre invites you,

### Expected behavior

The link should say the username of the person who made the group or who send the link.

**Comment by Mikatech** [comment]
Did you try to click on the button to find out more?

If not, I agree that even if the link is not visible in full, it should be possible to be directed to the good link but for now we need to click on find out more.

See this example:

![IMG_2415](https://user-images.githubusercontent.com/71339153/185164474-19e0a21f-8a11-4790-8ee3-6609ca4a5baa.png)

**Comment by LFGaming** [comment]
ah okay,, i did not know i had to press the read more button to have it function normaly,, it works normal when pressing read more,, oops
