### ISSUE TITLE
Text draft shows &#x2F for a /

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.429.3

### OS

iOS

### OS version

ios 15.5

### Device

iPhone 12 mini

### Steps to reproduce

1. Go to a chat,
2. Type `/` but not yet send it,
3. Go back to your screen where you can choose the chats,
4. It will show `Draft &#x2F` instead of a /

### Current behavior

It will show draft &#x2F instead of the /

### Expected behavior

It should show the /

**Comment by LFGaming** [comment]
Also happens with the & `&amp;`, " `&qout;`, ' `&#39;`, < `&lt;`, > `&gt;` characters

**Comment by jefft0** [comment]
@iuricmp says probably to do with HTML rendering. Will look at it.
