### ISSUE TITLE
Contacts: Long file name break chat UI

### ISSUE THREAD

**Issue by peletron** [berty/berty#4388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.431.1

### OS

iOS

### OS version

iOS 15.6.1

### Device

iPhone 13 Pro Max

### Steps to reproduce

1. Open Berty application 
2. Open some conversation 
3. Click on + button and add some file with long name

### Current behavior

You can see that UI is broken and user cannot see delivery status and time. Also in we have same issue for shared media section. 

![IMG_1821](https://user-images.githubusercontent.com/105677764/187262180-acdc847a-508c-4fae-aa21-43a00bf86cb5.png)

![IMG_1822](https://user-images.githubusercontent.com/105677764/187262244-f6650ac2-2443-4395-ba44-59f92318c315.png)

### Expected behavior

We should add ... to the long links or break them in few rows but do not break UI

**Comment by clegirar** [comment]
Hi, we deleted some non essentials features, like send a file, to be focus on the most important ones 👍
