### ISSUE TITLE
Create group: wrong background color

### ISSUE THREAD

**Issue by peletron** [berty/berty#4390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.431.1

### OS

iOS

### OS version

15.6.1

### Device

iPhone 13 Pro Max

### Steps to reproduce

1. Login to the Berty app 
2. Click on the + button at bottom right corner 
3. Click on the create group button

### Current behavior

Add member background is yellowish white. It is completely diffrent from any color that we have in application. If you move to the next screen, you will notice that Group info has same issue

![image](https://user-images.githubusercontent.com/105677764/187265838-b4b8141c-54ba-46dc-bc3c-64f8382eaabc.png)

### Expected behavior

This section should be white(#fff) and y search placeholder should be gray. For reference see color pallet of Inbox screen

**Comment by jefft0** [comment]
@iuricmp to change the colors to match Figma, which has the suggested colors.

**Comment by jefft0** [comment]
@iuricmp still working on it.

**Comment by jefft0** [comment]
@iuricmp still working on it.
