### ISSUE TITLE
Berty QR: Long user names affect position of QR code

### ISSUE THREAD

**Issue by peletron** [berty/berty#4391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.431.1

### OS

iOS

### OS version

iOS 15.6.1

### Device

iPhone 13 Pro Max

### Steps to reproduce

1. Navigate to the Berty app
2. Make sure user has some long name 
3. Click on the + Icon do add contact

### Current behavior

Long name affect position of Berty QR code. Code is shifted little bit to the left. 

![image](https://user-images.githubusercontent.com/105677764/187266762-8a742ef6-6dee-402f-933a-853a25cb2da7.png)

### Expected behavior

Berty QR code should be always placed in the middle of white layout.

**Comment by jefft0** [comment]
@iuricmp will make a PR to use an ellipsis for long display names in the QR screen and other placed.

**Comment by jefft0** [comment]
@iuricmp wrote the code for the change. Will make a PR.
