### ISSUE TITLE
Group: Creating empty group set status bar in never-end loading state

### ISSUE THREAD

**Issue by peletron** [berty/berty#4392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.431.1

### OS

iOS

### OS version

iOS 15.6.1

### Device

iPhone 13 Pro Max

### Steps to reproduce

1. Navigate to the berty app
2. CLick on + button at bottom right corner 
3. Create group 
4. Add all information and proceed with creating empty group

### Current behavior

Loading state should finish at some point or generate some error or log if something is wrong in background

### Expected behavior

Loading bar is stuck in never-end loading state, no matter how much wait it will be there. 
Adding one user to the group will resolve this issue, but it can appear later due to some other actions

**Comment by clegirar** [comment]
Hi, i re-enable it today 👍 With a new behavior, but you can have a behavior with a never-end loading state, its just that you don't find anyone on the group 👍
The next improvements on this feature will add some custom settings to `compact` or `hide` this bar if you don't want to see it 👍

**Comment by jefft0** [comment]
As clegirar mentioned, we are working on improvements to the member bar. But current behavior does not get stuck. So, closing this issue.
