### ISSUE TITLE
Appearance: Dark theme is broken for Settings page

### ISSUE THREAD

**Issue by peletron** [berty/berty#4396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.431.1

### OS

iOS

### OS version

15.6.1

### Device

iPhone 13 Pro Max

### Steps to reproduce

1. Login to the Berty application 
2. Navigate to the User settings
3. Click more than 7 times on app version to activate Devtool
4. Open Dev tools
5. Open appearance 
6.  Click on the Theme editor -> Switch to dark theme
7. Go back to the Settings

### Current behavior

Settings still have white theme for almost whole page and font is not visible at all. 
![IMG_1832](https://user-images.githubusercontent.com/105677764/187507857-bf419e57-4a77-4a38-9205-88bd3ab633d4.png)
![IMG_1833](https://user-images.githubusercontent.com/105677764/187507860-7d23c258-6ec4-43aa-943b-2a6fc027979d.png)

### Expected behavior

Settings page should be in dark theme as rest of the app

**Comment by EinsKatze** [comment]
Just wanted to add that this is a Problem on the _iPhone XS_, with _iOS 16_ and the _Berty Version v2.431.2_ aswell.

**Comment by clegirar** [comment]
Hi, we deleted some non essential features, to be focus on the most important ones  👍
