### ISSUE TITLE
Dev mode - All emojis and reaction in generated messages are shown as undefined

### ISSUE THREAD

**Issue by peletron** [berty/berty#4418]
### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
Mobile app

### Berty product version
2.431.2

### OS
Android

### OS version
Android 12 

### Device
Samsung Galaxy S21+

### Steps to reproduce
1. Log in to web app
1. Navigate to settings
1. Trigger Dev mode
1. Generate fake contacts, multi-members and messages
1. Navigate to any of messages 

### Current behavior
Currently any of the generated messages shows all emojis and reactions under all messages as "undefined" 
see attached video for explanation

https://user-images.githubusercontent.com/105677764/189753427-a7d40a75-f6d9-4b72-a887-1e0d6d09f2f1.mp4

**Comment by clegirar** [comment]
Hi, we delete some not essential features, to be focus on the more importants 👍
