### ISSUE TITLE
Provide a Flatpak as software package — for Linux systems

### ISSUE THREAD

**Issue by x80486** [berty/berty#4424]
### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
Desktop app

### Feature request
[Flatpak](http://docs.flatpak.org/en/latest/introduction.html) is a technology for building, distributing, installing and running applications – primarily targeted at the Linux desktop and desktop applications.

### Context
Distributing applications in this format makes it easy for users to install applications because they aren't packaged for a specific distribution.

**Comment by jefft0** [comment]
Hello @x80486 . There was a similar request for Flatpak in issue #3352 . As we said there: The Berty team doesn't have plans right now to create Linux package manager distributions, but we encourage the community to create them. If the time comes when you work on creating a package, please open a new issue.

Is this feature request different than #3352? If not, this issue will be closed in 14 days as a duplicate. Thank you.
