### ISSUE TITLE
Bootstrap Rendezvous StaticRelay MDNS 。Which configuration combinations enable the two clients to communicate

### ISSUE THREAD

**Issue by jc0803kevin** [berty/berty#4426]
### Asking a question, not reporting a bug
* [x] This question is not about a bug

### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
General

### Question
Bootstrap Rendezvous StaticRelay MDNS
Which configuration combinations enable the two clients to communicate？

### Context
Bootstrap Rendezvous StaticRelay MDNS
Which configuration combinations enable the two clients to communicate？

**Comment by jefft0** [comment]
Hello @jc0803kevin . This is difficult to reproduce with the information provided. Can you show the commands you are running?

**Comment by jefft0** [comment]
Perhaps this is an old project. If there are no more comments in 3 weeks, we'll close this issue.
