### ISSUE TITLE
Dev - Insufficiently used space doesn't allow preview of whole name for features

### ISSUE THREAD

**Issue by peletron** [berty/berty#4427]
### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
Mobile app

### Berty product version
2.431.2

### OS
Android

### OS version
Android 12 

### Device
Samsung Galaxy S21+

### Steps to reproduce
1. Log in to app
1. Navigate to the Settings page
1. Trigger dev mode
1. Navigate to Dev tools
1. Navigate to Appearance -> Theme Editor

### Current behavior
Even when there is plenty of unused space regarding width of the screen names won't be fully shown and will prematurely be cut off. 

![1](https://user-images.githubusercontent.com/105677764/190605795-ed80cf27-d9fe-473d-b966-62e7f82995bc.jpg)

**Comment by LFGaming** [comment]
Seems to be fixed on both my iphone 12 mini, and my samsung galaxy S20, anyone that can confirm?

**Comment by jefft0** [comment]
Put in backlog for when we have more time for low-priority UI bugs.
