### ISSUE TITLE
Account: When changing Username, Input gets behind the Keyboard

### ISSUE THREAD

**Issue by EinsKatze** [berty/berty#4435]
### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
Mobile app

### Feature request
The Username Input gets hidden behind the Keyboard when changing it, at least on IOS.
Maybe make the Account Change Window like a PopUp or move it to the Top.
![Keyboard Hides Username Input](https://user-images.githubusercontent.com/82060534/191720585-7a31344a-3d46-4153-a878-5fdfa8322ac5.gif)

### Context
You cannot see what you are typing, which causes you to misspell your name and have to type it again.

**Comment by EinsKatze** [comment]
This can also be considered as a bug i guess.

**Comment by zeusz3** [comment]
I could not replicate this on Samsung S21 android 13

**Comment by zoli** [comment]
Can't replicate this on Xiaomi Redmi. Maybe its IOS only?

**Comment by jefft0** [comment]
Verified on 23/3/23 .
