### ISSUE TITLE
dark mode on Android

### ISSUE THREAD

**Issue by khimaros** [berty/berty#4438]
### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
Mobile app

### Feature request
dark mode would be great to have!

### Context
preserve my retinas for a rainy day

**Comment by jefft0** [comment]
Hello @khimaros . Is this feature request different than https://github.com/berty/berty/issues/4091 ?

**Comment by khimaros** [comment]
I don't see a dark mode toggle in my berty settings at all.

**Comment by RageGamerBoi** [comment]
> Hello @khimaros . Is this feature request different than #4091 ?

That's for IOS
Android doesn't have a dark mode properly implemented at all.
