### ISSUE TITLE
Linux cli berty

### ISSUE THREAD

**Issue by CaStrayOne** [berty/berty#4458]
### Asking a question, not reporting a bug
* [x] This question is not about a bug

### Is there an existing issue for this?
* [x] I have searched the existing issues

### Berty product
CLI tools (berty mini, daemon, etc.)

### Question
Hello!  Everything is fine, but I don't know how to send and receive messages in Linux, please help me, thanks.

### Context
This Is a question about using this app on Linux (CLI)

**Comment by jefft0** [comment]
Hello @CaStrayOne . Are you able to install and run the berty CLI by following the README? https://github.com/berty/berty/blob/master/go/README.md

The help screen is the best documentation at the moment.

**Comment by digital-idiot** [comment]
Hi @jefft0 
I also have the same question. I installed `berty` (Linux) on my laptop and android app on my phone. I generated QR code using `/contact share qr` and then scanned it on my phone to send a chat request. I accepted the request using `/contact accept all` just to be sure, and on the phone I see that the request has been accepted. Now I sent messages from my phone which appears as **sent** but I am not sure how to view / reply to them from my laptop. The `/help` does not have any clarity regarding this.  In general, how am I supposed to switch contacts / groups to chat respectively?

**Comment by jefft0** [comment]
Hello @digital-idiot. To switch contacts/groups, use ctrl-P and ctrl-N .
(Sorry that it isn't very well documented. This was originally created as a testing tool by the developers who are familiar with this code:
https://github.com/berty/berty/blob/680aed021e43c5640a66533db3253469b0b0520b/go/cmd/berty/mini/main.go#L151-L167 )

**Comment by CaStrayOne** [comment]
> Hello @CaStrayOne . Are you able to install and run the berty CLI by following the README? https://github.com/berty/berty/blob/master/go/README.md
> 
> The help screen is the best documentation at the moment, especially the help screen for berty mini which can be used to send messages.
> 
> <blockquote><img src="https://repository-images.githubusercontent.com/141089889/bb009800-7059-11ea-935c-8e7a99aec447" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/berty/berty">berty/README.md at master · berty/berty</a></strong></div><div>Berty is a secure peer-to-peer messaging app that works with or without internet access, cellular data or trust in the network - berty/README.md at master · berty/berty</div></blockquote>

Hi, yes, I just haven't been able to send the message through the laptop.  And also the help page clearly has no information about this!

**Comment by LFGaming** [comment]
I don't know if input or help is still needed but for me it works fine with ubutnu on WSL and an iphone. By sending `/contact share qr` I get my qr code, then i scan that with my iphone, and on my laptop i sen `/contact accept all` then with `ctrl + n` I can go to the chats below, alternatively you can use `ctrl + arrow up` to go to the chat above (and your account) or `ctrl + arrow down` to go to another chat below (so just navigate the chats you see on the left bar). I hope this helps, if not Ill try to help more :)

**Comment by bluebluecard** [comment]
Hello, I git clone the berty on ubuntu 22.04 and then I try to use command "go run mini.go" in go/cmd/berty directory, but it failed and return error information:
# command-line-arguments
./mini.go:18:3: undefined: manager
./mini.go:19:3: undefined: manager
./mini.go:20:3: undefined: manager
./mini.go:21:3: undefined: manager
./mini.go:22:3: undefined: manager
./mini.go:23:3: undefined: manager
./mini.go:24:3: undefined: manager
./mini.go:33:19: undefined: ffSubcommandOptions
./mini.go:34:19: undefined: usageFunc
./mini.go:41:4: undefined: manager
./mini.go:41:4: too many errors

can you tell me what I should do next to fix it?

**Comment by LFGaming** [comment]
@bluebluecard 
To run berty mini you have to run the command `berty mini`.
`go run mini.go` gives me the same errors

**Comment by bluebluecard** [comment]
I run the command 
make install in the berty/go directory and it is successful.

and if I run berty mini, it returns
command not found: berty.

But I run make doctor, it shows there is no problem.

**Comment by LFGaming** [comment]
Hi @bluebluecard 
I had to add my go to my bashrc file when I tried to use berty for the first time in my cli, do you have go installed correctely?

I had to add `export PATH="$PATH:$HOME/go/bin"` to my ./bashrc and then it worked correctely for me.

**Comment by bluebluecard** [comment]
Thanks for your reply.
Yes, I add the go/bin into .bashrc and if i run go version, it is ok.

Can you show me your steps of installing berty on your linux computer? I want to repeat it.

**Comment by bluebluecard** [comment]
I found berty was installed in another directory, now I can run it.

**Comment by jefft0** [comment]
@CaStrayOne , do you have more questions about this issue? If not, then in 21 days we'll close it as resolved.

**Comment by jefft0** [comment]
No more questions. Closing as resolved.
