### ISSUE TITLE
App

### ISSUE THREAD

**Issue by Moobitz** [berty/berty#4477]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Question

How do I install on android

### Context

Usage

**Comment by jefft0** [comment]
Did you try the link to Google Play on the web site?
https://berty.tech/

**Comment by jefft0** [comment]
Hello @Moobitz . Did the above comment solve your problem? If there are no more questions, then in 21 days we will close this issue as resolved.

**Comment by jefft0** [comment]
Closing as resolved.
