### ISSUE TITLE
No longer prebuilt binaries?

### ISSUE THREAD

**Issue by RubenKelevra** [berty/berty#4482]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Desktop app

### Question

The new release 2.435.0 is published only as source code. There's no prebuilt binary.

Is this intentionally, so will there be no longer prebuilt binaries in the future?

### Context

I'm the package maintainer for Berty and Berty-Gui for ArchLinux's AUR:

https://aur.archlinux.org/packages/berty-bin
https://aur.archlinux.org/packages/berty-gui-bin

These are binary packages, so only fetch your binary and install it - no compilation.

**Comment by jefft0** [comment]
@RubenKelevra , I don't know what happened with release 2.435.0. The latest release 2.436.0 has binaries. Does fix your problem?
https://github.com/berty/berty/releases/tag/v2.436.0

**Comment by jefft0** [comment]
The last two releases have binaries. The release process seems to be working. There was only one release without binaries. We don't have the resources to investigate why that one release didn't have binaries, so I think we can close this issue.
https://github.com/berty/berty/tags
