### ISSUE TITLE
Better Integrate libp2p as a bluetooth transport layer

### ISSUE THREAD

**Issue by TheRook** [berty/berty#4517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

I noticed that berty uses the libp2p protocol in an interesting way.  libp2p has a bluetooth transport layer that isn't as advanced as berty, but is an important part of the project readmap as libp2p should be reachable over bluetooth radios:
https://github.com/libp2p/js-libp2p/blob/master/src/circuit/README.md

Code:
https://github.com/libp2p/rust-libp2p/pull/971

Berty's mesh protocol is better than libp2p's.  Would it be possible for you to push some of your bluetooth peer-networking discoveries up stream to the libp2p community?  The bonus is that after it is accepted by libp2p the community will hack on it and maintain it - and Berty can benefit by using the libp2p common library. 

### Context

Integration request with libp2p's bluetooth stack. 

### Possible implementation

libp2p, a library that Berty depends on, could adopt a better solution for its bluetooth networking that is community maintained.

**Comment by jefft0** [comment]
Hello @TheRook . To be clear, are you asking us to push our Go code so that you can refer to it for the rust-libp2p implmentation?

**Comment by jefft0** [comment]
There haven't been any more questions for 3 weeks. We already submitted our BLE driver to the go-libp2p project. We may be working with Rust in the future, but closing for now.
