### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by itsunixiknowthis** [berty/berty#4551]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

CLI tools (berty mini, daemon, etc.)

### Question

Hello,

Can you confirm receipt of the security advisory we sent to you on October 30, 2022 from itsunixiknowthis@zohomail.com to bertytech@protonmail.com and secure@berty.tech?

We have just resent it right now, please check spam folder, or help us establish a private channel to you, so we can send you more advisories in the future.

Best regards.

### Context

xxx

**Comment by sudwhiwdh** [comment]
My observation is that the linked one at
https://berty.tech/contact `secure@berty.tech` has not been working for a while. Tried it again earlier and I get the following error message:

```
Delivery Status Notification (Failure)

Address not found
Your message was not delivered to secure@berty.tech 
```

**Comment by sudwhiwdh** [comment]
By the way, the error message comes from mailer-daemon@googlemail.com. Do you use or have used Gmail for your mail infrastructure?

**Comment by jefft0** [comment]
No more comments from poster. Closing as resolved.

**Comment by sudwhiwdh** [comment]
@jefft0 I had trouble finding the issue again.
Can you please move it to https://github.com/berty/www.berty.tech?
