### ISSUE TITLE
Upload recent version of Berty on Google Play and App Store

### ISSUE THREAD

**Issue by Amir-Arsalan** [berty/berty#4552]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Question

The most recent version of Berty is not uploaded on Google Play and App Store

### Context

It's been a while that the new version of Berty has not been posted to Google Play (even for beta testing) and App Store. Could you please post the new versions there? Also, would you mind uploading the .apk file of Berty here on GitHub after each release of the app?

Thanks

**Comment by LFGaming** [comment]
Hi @Amir-Arsalan,

You can donwload the apk here on discord at https://github.com/berty/berty/actions/workflows/android.yml and then choose the most recent succeded build, then at the bottom you can download an Artifact which is the apk of the latest build.
It will not (yet) be added to the github or website as stated by @glouvigny in the discord where he said the following:

> you can download it from the Github action flow, as of now there are no plans on adding the download on the website nor the Github releases section.

as for the update to the App store and Play Store, I don't know when it will be updated, sorry.

**Comment by Amir-Arsalan** [comment]
@aeddi @gfanton @glouvingny Just tagging you in case you could help with this.

@LFGaming I just tried downloading one of the .apk files from the bottom of [one of the Actions](https://github.com/berty/berty/actions/runs/3968500296)  but there is no file there (there is no link). Should I look somewhere else?

**Comment by LFGaming** [comment]
I took a look at the action you chose, and i see an downloadable .apk at the bottom. But I also just saw that when i use the github app i don't see the apk part,, so maybe try it on your web browser?
![image](https://user-images.githubusercontent.com/38732192/214262353-bc9689b7-54d2-40e1-a97b-a2eed076b42b.png)
![image](https://user-images.githubusercontent.com/38732192/214262495-e7ebab09-2d8d-4bf0-b9d6-84f932011476.png)

**Comment by Amir-Arsalan** [comment]
@LFGaming I tried my Browser but the file you see does not have a link for downloading it. You cannot click on it when you open it with your Browser :)

@jefft0 do you know what people should do to download a recent version of the app seamlessly?

**Comment by jefft0** [comment]
I see the same thing that LFGaming shows in the screenshot. I can click and download it.

**Comment by jefft0** [comment]
...A question for you, @LFGaming . If you log out of Github, can you still use your browser to click and download the apk?

**Comment by LFGaming** [comment]
Hi @jefft0, just tried it without being logged in,, and it indeed seems i can then not download the .apk artifact.

**Comment by jefft0** [comment]
Thank you for taking the time to check. I did a search and it seems that this is a known issue. https://github.com/actions/upload-artifact/issues/51 .
@Amir-Arsalan, you are posting as a Github user. Is it possible for you to log into a browser as a Github user and download the apk?

**Comment by Amir-Arsalan** [comment]
@jefft0 @LFGaming Sorry I was not logged in when I tried to download the .apk file. I can download it when I log in. However, I cannot do this for my iPhone as for iOS any app has to get installed through the App Store. What is the issue that the app is not updated on Google Play and App Store?

**Comment by LFGaming** [comment]
Hi @Amir-Arsalan I talked with manfred and you can use this qr code to download the latest version of the berty app op IOS at this point:
![image](https://user-images.githubusercontent.com/38732192/214708310-69d3a05b-357a-4148-af05-169d7982fd5f.png)
You might need to allow it to be used in the settings of your phone

**Comment by LFGaming** [comment]
Hi @Amir-Arsalan I got the news that there will come a new version of the testflight release for the community, which should be ready next week. You can use that when its ready to have the latest version of the app.

**Comment by sudwhiwdh** [comment]
@clegirar 
Out of curiosity, may I know what made you as a team not update the versions in the named stores for a while?

**Comment by LFGaming** [comment]
Hi, @Amir-Arsalan and @sudwhiwdh the team told me that they wanted to wait for a stable version before the offical app store and play store version get updated, but there (should) be a testflight version next week. And the android versions you can always download on github at the actions page like explained above,, or on the discord server. Hope this helps.

**Comment by jefft0** [comment]
@Amir-Arsalan, do you have more questions about this issue. If not, then in 21 days we'll close it as resolved.

**Comment by jefft0** [comment]
No more questions. Closing as resolved.
