### ISSUE TITLE
Make a Precompiled APK File Available

### ISSUE THREAD

**Issue by RageGamerBoi** [berty/berty#4602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

A precompiled APK File available every Github release, or on the website.

### Context

For people who don't have Google Play on their Android phones.

**Comment by LFGaming** [comment]
On the github actions you can click android and then at the bottom (if you are logged in on github) you can find a artifact which is a precompiled android apk, you can also find them on the discord,
for more information please look at: [This github issue](https://github.com/berty/berty/issues/4552)

**Comment by RageGamerBoi** [comment]
Ah ok, thanks!
Adding it to the Github releases page would probably be ideal, but it’s good that it’s available :)
