### ISSUE TITLE
[l10n] Please add Lithuanian language to Crowdin

### ISSUE THREAD

**Issue by welaq** [berty/berty#4652]
I sent a message in Crowdin a month ago but did not get an answer. So I guess I will have to ask here.

FYI @moul

**Comment by jefft0** [comment]
@iuricmp to check the language configuration on Crowdin. We also need to wait until after the translation folder location is update in the Berty code.

**Comment by iuricmp** [comment]
Hi @welaq ,

We added Lithuanian language support as requested.
Please, check it here: [https://translate.berty.community/berty/lt](https://translate.berty.community/berty/lt)
