### ISSUE TITLE
Suggestion: Add a 'Vault' feature

### ISSUE THREAD

**Issue by jreamy** [berty/berty#4658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

Berty already supports storing images and files by sending them to a group. It would be nice to be able to store images and files independent of a group in a vault/password manager style. It would also be nice to be able to share documents / images with individual contacts outside of a specific group.

### Context

Similar to https://github.com/berty/berty/issues/4657, this is about adding secure p2p document storage that is easy for the end user to use. It could evolve into a fully fledged password manager, or remain a simple way to securely transfer documents between your own devices.

**Comment by jefft0** [comment]
Due to the security design mentioned above, Berty Messenger will not be implementing a "share document" feature. Do you want to clarify the feature, or can we close the issue?

**Comment by sudwhiwdh** [comment]
Oh, I would like to add: For me, communication has even more forms of expression than pure text messages. I see images and spoken language as a part of communication as well.

**Comment by jefft0** [comment]
Closing as won't implement, with explanation why not.
