### ISSUE TITLE
App gets stuck on loading screen

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

V2.468.0

### OS

iOS

### OS version

iOS 16.4.1 (a)

### Device

iPhone 12 mini

### Steps to reproduce

1. Remove app
2. Download version V2.468.0 (latest at this point)
3. Make an account
4. After the making you will be stuck at the three dots that bounce up and down

### Current behavior

Currently if you update to version V2.468.0 the app will freeze at the `setup-local-messenger-server` screen. See Image:
![Screenshot_20230505_140507_Berty_Yolo](https://user-images.githubusercontent.com/38732192/236457327-869c08f9-c1d1-4004-a85b-1830f717db7a.jpg)

If you delete the app and redownload the following will happen:
iOS:
You can make an account but after finishing your account making you will get stuck at the three dots screen. See image:
![IMG_7758](https://user-images.githubusercontent.com/38732192/236457811-89ce01dd-659e-4e0d-8a25-c2fa364a2945.png)

Android:
Some times the app freezes at the following screen:
![Screenshot_20230505_141017_Berty_Yolo](https://user-images.githubusercontent.com/38732192/236457979-45c62e59-c19b-49dc-872c-ad51eebf063e.jpg)
This does not happen everytime after removing and reinstalling the app so it might be something else

### Expected behavior

It should not freeze.

**Comment by LFGaming** [comment]
> I have also seen Berty get stuck at "setup-local-messenger-server".

For me it seems to be very in consistent, sometimes when redownloading the app it works and sometimes it freezes

**Comment by LFGaming** [comment]
Now in version 2.468.3 it freezes always when starting the app for me. but it seemed to be fixed in between the versions.
Anyone that can confirm that it always freezes in version 2.468.3?

**Comment by jefft0** [comment]
@LFGaming : Yes I just tried restarting 2.468.3 on my iPhone 14 and it is stuck at "setup-local-messenger-server".

**Comment by LFGaming** [comment]
After a bit of trying around I found the following:
When using two phones, in my tests they where a iPhone 12 mini running iOS 16.4.1 and an Samsung Galaxy S20 5G running Android 12. With Berty versions: Android version v2.268.2.dev.2, iOS version: 2.468.3

When I had my iphone on and made a chat with the Android that was online everything went fine.
restating the iPhone app while the android was still on and had berty open itt all goes well, but when I restart the iPhone app while the android did not have the app open the iPhone freezes.

See video for explenation:
https://github.com/berty/berty/assets/38732192/2c90d64d-714e-482b-8b84-99624173129f

</br>

It seemed that when i turned the Bluetooth settings on in the berty app this all was not a problem anymore, and the iPhone app just starts as it should without any freezes, but this could maybe be a coincidence?

I hope this helps in fixing the bug :)

**Comment by jefft0** [comment]
Log message of possible cause of the freeze:
023-05-31 10:26:06.919816+0200 Berty Staff[75750:792716] [bertybridge.bty.gorm] [ERROR] trace    {"error": "sql: converting argument $1 type: unsupported type clause.Expr, a struct", "elapsed": "12.625µs", "rows": 0, "sql": "INSERT INTO `accounts__temp`(`public_key`,`display_name`,`link`,`replicate_new_groups_automatically`,`auto_share_push_token_flag`,`device_push_token`,`device_push_server`,`muted_until`,`hide_in_app_notifications`,`hide_push_previews`) SELECT `public_key`,`display_name`,`link`,`replicate_new_groups_automatically`,`auto_share_push_token_flag`,`device_push_token`,`device_push_server`,`muted_until`,`hide_in_app_notifications`,`hide_push_previews` FROM `accounts`"}

**Comment by D4ryl00** [comment]
bug introduced by PR #4669

**Comment by D4ryl00** [comment]
bug introduced by our deps ` gorm.io/gorm v1.23.6`

**Comment by D4ryl00** [comment]
bug introduced by commit `93986de8e43bc9af6864621c9a4855f0f860cde2` of `gorm.io/gorm`

**Comment by jefft0** [comment]
Hi @LFGaming . In the latest TestFlight, this bug is fixed for me. Is it fixed for you?

**Comment by jefft0** [comment]
Great! Thanks for testing.
