### ISSUE TITLE
Push notifications not working since v2.464.0

### ISSUE THREAD

**Issue by D4ryl00** [berty/berty#4685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

v2.464.0

### OS

iOS

### OS version

Android + iOS version

### Steps to reproduce

On both onboarding and conversations, you will not be able to activate push notifications.and

### Current behavior

Push notifications are not received.

### Other

This issue is due to a migration of the push notification system from weshnet to Berty.
During this long task, the push notifications are disabled in the codebase.
You can follow the work in this PR: https://github.com/berty/berty/pull/4637

**Comment by jefft0** [comment]
Keep open as tracking issue for the community.

**Comment by glouvigny** [comment]
Hi, since you don't describe what is not working that might be related, I can't opt-in to push notifications, no errors are displayed. 

I am using a phone on Android 13 running the v2.468.16 from Play Store

https://github.com/berty/berty/assets/486708/b360eb0d-e962-4522-b14c-680e20eeed4a

**Comment by D4ryl00** [comment]
Hi @glouvigny :)
The PR (https://github.com/berty/berty/pull/4637) that should fix the push notification system is almost done. We should still fix the deep links before merging it.
Since we have higher priorities, we don't find the time to fix that :/
Stay tune ;)
Thanks!

**Comment by jefft0** [comment]
PR https://github.com/berty/berty/pull/4637 to fix push notifications is tested and merged. We will make a new store release soon.

**Comment by jefft0** [comment]
The fixed version is released on App Store and Google Play. Closing.
