### ISSUE TITLE
Some buttons in dev settings have long names

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

Android version v2.268.2.dev.2, iOS version: 2.468.3

### OS

iOS

### OS version

Android version 12 and iOS version 16.4.1

### Device

iPhone 12 mini and Samsung Galaxy S20 5G

### Steps to reproduce

1. Go to the dev settings
2. Some of the settings have long names

### Current behavior

Some of the buttons have long names like: `settings.home.linked-identities-b... ` or `settings.home.directory-search-b...`

See image:
![photo_6030493332284750616_y](https://github.com/berty/berty/assets/38732192/163abd1d-573a-4a82-94c1-ed4c6fd4877e)

### Expected behavior

would expect it to have shortened names like: `linked idetities` and `directory search`

**Comment by jefft0** [comment]
Hello @LFGaming . I verified the bug. I agree that the setting name is not clear. By the way, the screen shot image above doesn't work. If it is easy, can you upload a screen shot? (If it's too much trouble, don't worry. The description is clear enough.)

**Comment by LFGaming** [comment]
Hi @jefft0 I added a screenshot, for me this one does work, can you confirm?

**Comment by jefft0** [comment]
The screen shot looks good. Thanks!
