### ISSUE TITLE
App crashes when turning Bluetooth mode on

### ISSUE THREAD

**Issue by LFGaming** [berty/berty#4733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

V2.468.13-dev.10+…

### OS

Android

### OS version

Android 13

### Device

Samsung galaxy S20 5G

### Steps to reproduce

1. Open the app
2. Go to settings
3. Enable Bluetooth
4. Go back to Home Screen (the app will reload)
5. While reloading it crashes

also happens on other android phones (os versions of these phones I do not know)

### Current behavior

The app crashes when you enable Bluetooth mode on android.

https://github.com/berty/berty/assets/38732192/78fd39cd-24f9-4864-b7fb-448386c63a81

### Expected behavior

It should not crash

### Other

This bug came into existence after the update to Android API 31.

**Comment by leonderdunna** [comment]
also happens on Pixel 7 Pro with Android 13

**Comment by jefft0** [comment]
Re-open this bug until the fix is release on the app stores.
