### ISSUE TITLE
can i use @berty/api directly?

### ISSUE THREAD

**Issue by tonyzzp** [berty/berty#4745]
### Asking a question, not reporting a bug

- [x] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Desktop app

### Question

I want to create an electron app for windows with vue.
If i use berty.exe directly, how should I communicate to berty whith vue?
Can i use @berty/api directly?  such as:

```
beapi.account.AccountService.create(impl,... )
```
how could I implement the impl?

### Context

nothing

**Comment by n0izn0iz** [comment]
No you should run your own protobuf codegen like https://github.com/stephenh/ts-proto with buf https://buf.build/
