### ISSUE TITLE
berty_windows_amd64.zip 这个打开就一个小黑屏，然后点击就自动关闭了啊，咋使用windows的版本

### ISSUE THREAD

**Issue by qidouhai** [berty/berty#4746]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Desktop app

### Question

不知道咋使用

### Context

没明白咋使用这个软件，因为我的手机上有APP，所以电脑上也想下载一个桌面版的软件，方便使用，下载之后发现不能正常使用，请问是应该如何使用呢？

**Comment by jefft0** [comment]
English, please.

**Comment by jefft0** [comment]
No more questions after the reply. Closing as resolved.
