### ISSUE TITLE
F-droid release

### ISSUE THREAD

**Issue by GameOverFlowChart** [berty/berty#4758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

Release the Android app on F-droid (in the official repo and optionally also a custom repo).

### Context

This will make it easier to discover the app, make you and the users less dependent from the Playstore. Also if the app is added to the official F-droid repo, this will increase the trust to the app.

**Comment by jefft0** [comment]
Hello @GameOverFlowChart . This already has an issue #3101 . Can you add your comments to that issue, so that we can close this as duplicate?

**Comment by GameOverFlowChart** [comment]
> Hello @GameOverFlowChart . This already has an issue #3101 . Can you add your comments to that issue, so that we can close this as duplicate?

I did 👍

**Comment by jefft0** [comment]
Poster has added comments to the original issue #3101 . Close as duplicate.
