### ISSUE TITLE
Inquiry Regarding Removal of Bazel Build Tool Support

### ISSUE THREAD

**Issue by mahmoud-alfadel** [berty/berty#4772]
### Asking a question, not reporting a bug

- [x] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

General

### Question

I would like to inquire about the removal of Bazel build tool support in the berty project. Could you please provide insights into the reasons behind this decision and whether there are plans to reintroduce support for Bazel in the near future?

### Context

I am doing some experimental analysis to understand the rationale behind removing Bazel.

Any help would be highly appreciated. Thanks!

**Comment by n0izn0iz** [comment]
The short version is: because of no official support for react-native and gomobile
I had some parts working but it was a huge pain and we don't have enough manpower to maintain it vs the benefit it gives

**Comment by jefft0** [comment]
Hello @mahmoud-alfadel . Does the response resolve your question?

**Comment by jefft0** [comment]
No more feedback from the poster to the response. Close as resolved.
