### ISSUE TITLE
The new Berty update crashes on launch iOS 14

### ISSUE THREAD

**Issue by xXG0DLessXx** [berty/berty#4793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.469.9

### OS

iOS

### OS version

14.8

### Device

iPhone SE (Gen1) 2016 version

### Steps to reproduce

1. Download app
2. Open app
3. Crashes

### Current behavior

The app crashes. Here the crash log from the iOS settings analytics section:
[Berty-2024-01-15-113559.txt](https://github.com/berty/berty/files/13938001/Berty-2024-01-15-113559.txt)

### Expected behavior

The app should launch and work

**Comment by LFGaming** [comment]
Hi,
For me it all works fine after a clean install of the app. With a Iphone SE first gen, iOS 14.3

**Comment by xXG0DLessXx** [comment]
> Hi, For me it all works fine after a clean install of the app. With a Iphone SE first gen, iOS 14.3

Hmm.. very strange, but it does indeed seem to be working now for me as well… I did the following:
1. Delete Berty.
2. Reboot the phone.
3. Reinstall Berty fresh.
4. Now it just works… no idea what exactly happened there… maybe the crash log can still provide some insight? It’s not ideal to have to reinstall the app and lose data…

**Comment by jefft0** [comment]
We'll take note of the crash log and decide if there is something to fix. Please let us know if you have any more feedback. Otherwise we can close this.
