### ISSUE TITLE
Update libp2p

### ISSUE THREAD

**Issue by jefft0** [berty/berty#4799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

This is a tracking issue to update libp2p

### Context

This may allow us to merge some dependabot PRs like https://github.com/berty/berty/pull/4792

**Comment by jefft0** [comment]
After fixing this, revisit the dependabot issues mentioned above.

**Comment by jefft0** [comment]
@D4ryl00  will start with updating libp2p in the dependencies (go-ipfs-log, go-orbit-db, weshnet).

**Comment by jefft0** [comment]
First need to resolve the test addressed in https://github.com/libp2p/go-libp2p-pubsub/pull/536

**Comment by jefft0** [comment]
> First need to resolve the test addressed in [libp2p/go-libp2p-pubsub#536](https://github.com/libp2p/go-libp2p-pubsub/pull/536)

PR #536 has been closed. They say that the same fix is merged in a [different PR](https://github.com/libp2p/go-libp2p-pubsub/pull/564). 
https://github.com/libp2p/go-libp2p-pubsub/pull/536#issuecomment-2222733276

**Comment by jefft0** [comment]
Updated libp2p in https://github.com/berty/go-ipfs-log, https://github.com/berty/go-orbit-db, https://github.com/berty/go-libp2p-mock, https://github.com/berty/go-libp2p-rendezvous and https://github.com/berty/go-ipfs-repo-encrypted . Still resolving dependency issues in weshnet and berty.

**Comment by D4ryl00** [comment]
fixed by https://github.com/berty/berty/pull/4866
