### ISSUE TITLE
Allowing non-contacts to act as relays for each other

### ISSUE THREAD

**Issue by Redbaron29** [berty/berty#4800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

Hey guys, I’ve been working on integrating a dew computing protocol into the Berty architecture, but before I go too much further (I tried with Briar but it wasn’t compatible), I was hoping for some advice.

My protocol called Spatial Temporal Connection  (STC) functions by broadcasting pending messages via wifi/BTE when the internet is unavailable. It creates a sort of “pseudo”-MANET by relaying messages through user movement over time. It would stack perfectly on top of the wesh protocol, but the only thing holding me back is finding a way to relay messages between non-contacts; meaning two or more Berty users that are NOT part of the same group or even share the same contacts.
I can go into more detail about it if need be, but can anyone tell me if this is possible with Bertys architecture or would this break too much?
Thanks!

### Context

This could be used to create a massive mesh network between devices running the app.

**Comment by jefft0** [comment]
We can looked at using the mobile phone as a general relay but did not implement this. It uses too much battery, and there are some security concerns. Currently, when a user's mobile relays messages, the user is already in the same message group.

**Comment by jefft0** [comment]
No more comments. Closing.
