### ISSUE TITLE
How long before Berty enters the stable phase

### ISSUE THREAD

**Issue by hhbisheng** [berty/berty#4806]
### Asking a question, not reporting a bug

- [X] This question is not about a bug

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Question

When can Berty end the testing? I have been following Berty for three years, and there will be Berty in 2021

Warning: Berty is still under active development and should not yet be used to exchange sensitive data.

I have also encountered serious network issues while using Berty, and adding friends requires a very long waiting time. I think this is due to the impact of China's IPFS environment.

Berty may be able to directly import the other party's IPv6 and port when adding contacts, which can quickly connect to their network.

This may be a way to avoid IPFS network failures.

### Context

Looking forward to more features, such as voice and video

**Comment by costinberty** [comment]
Hi! We built Berty Messenger app to showcase our flagship product, the [Wesh Network](https://wesh.network/) communication protocol. Regarding the app's stability, we are constantly working to improve it and make it more stable and reliable. We have just released the latest version of the app on both App Store and Play Store.

**Comment by hhbisheng** [comment]
Thank you for your work, it is very meaningful. When can Berty become a mature solution @costinberty
