### ISSUE TITLE
Toggle button out of the screen

### ISSUE THREAD

**Issue by SujalLama** [berty/berty#4823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

2.469

### OS

Android

### OS version

Android 12

### Device

Galaxy M21

### Steps to reproduce

1. Click on Profile icon after you sign in 

### Current behavior

![bdb5edbe-8def-4c65-9433-d312a74b5048](https://github.com/berty/berty/assets/71555740/f36f0b05-0e04-42d6-a0ac-bc32d8f43af4)

### Expected behavior

The toggle button should not go out of the screen

**Comment by jefft0** [comment]
I confirmed the misaligned toggle in the iOS simulator. This may be related to the React-Native version. Let's revisit after updating React-Native.

**Comment by jefft0** [comment]
@iuricmp will try a minor upgrade of React Native.
