### ISSUE TITLE
Connect via ID instead of qr code.

### ISSUE THREAD

**Issue by rattailgamer** [berty/berty#4842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Feature request

An ID that can be entered instead of scanning the QR code. Also the option to scan from a picture would eb nice.

### Context

I to give my connection to someone on the other side of the world. So it would be nice if I could tell them an ID that they could enter instead of the QR code. Also I have another high security device that doesn't have a camera or microfon, so I can`t use the app on that device anyways.

**Comment by costinberty** [comment]
Hi @rattailgamer ! thank you for reaching out. 

We understand the use of having another way besides the QR code to connect to another user. For the moment we do not have the bandwidth to add a more straightforward and also secure way of sharing contacts. 

However, there is a way you can do this by sharing an URL with the other user. These are the steps to follow:
1. Click on + 
![IMG_4391](https://github.com/berty/berty/assets/109347079/91ac484e-a850-46da-abf8-e841a080c6de)

2. Click on the link 
![IMG_4392](https://github.com/berty/berty/assets/109347079/e0254df7-1787-42cd-9366-ffe15221a70b)

3. Copy the link and send it to the person you want to connect with via another secure mail/message app

**Comment by rattailgamer** [comment]
thanks for the answer. :)

**Comment by jefft0** [comment]
No more comments from the poster. Closing as answered.
