### ISSUE TITLE
Download app on two iPhones, connected one to other with QR and I cannot message between them

### ISSUE THREAD

**Issue by macrigiuseppe** [berty/berty#4847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Berty product

Mobile app

### Berty product version

v2.470.3

### OS

iOS

### OS version

17.5.1

### Device

iPhone 15 Pro

### Steps to reproduce

1. Download the app in two different iPhones
2. create two different usernames
3. add one username to the other using the QR
4. the invitation is still pending but the other phone never receives the invitation request

### Current behavior

![IMG_0812](https://github.com/berty/berty/assets/2554552/00d010ee-b415-4b23-b853-173d5efb0bb4)

### Expected behavior

I should be able to add the other user. the other user should receive the notification and start messaging

**Comment by macrigiuseppe** [comment]
my contact never receive a notification to connect, when trying to re-send the contact request the application doesn't do anything

**Comment by jefft0** [comment]
Hello @macrigiuseppe . We restarted the rendezvous server. I tested on my two phones. It's working. Can you please try again?

**Comment by macrigiuseppe** [comment]
hey @jefft0, thank you for restarting the server. 
Unfortunately I tried with no luck. I also uninstalled the app on both iPhones and re-installed, added each other as contact but still no luck

**Comment by costinberty** [comment]
@macrigiuseppe thanks for engaging with us on this; we are still experiencing some issues with the RDV node (which is used for sharing contacts via QR). We are looking into this and we will fix it (hopefully next week).

**Comment by xrayid** [comment]
Faced the same issue on IOS.
Any updates?

**Comment by D4ryl00** [comment]
We are working on updating IPFS and libp2p on all our stacks, which are two major Berty dependencies.
The next step would be to investigate the inconsistent connection issue you can observe.
We will give you more information as we find something.
Thanks.

**Comment by xrayid** [comment]
Hello @D4ryl00
Thank you for the additional information

**Comment by jefft0** [comment]
Hello @macrigiuseppe . @D4ryl00 mentioned that we were updating libp2p. This is now completed and the service for sending contacts is fixed. There is a new Berty Messenger on the Apple App Store. (Not on the Google Play Store yet.) Can you please try again?

**Comment by jefft0** [comment]
The iPhone version is updated and working. No more comments from the original poster. Closing as resolved.
